### ISSUE TITLE
IllegalArgumentException: measure is called on a deactivated node

### ISSUE THREAD

**Issue by Villainous-SatCure** [MM2-0/Kvaesitso#1000]
## The app keeps crashing when typing fast

*when i try to type something the app suddenly crashes, this happens when i try and type fastly, it crashes constantly and i have to re-asign the launcher everytime it happens.*

## Strack trace

```
java.lang.IllegalArgumentException: measure is called on a deactivated node
	at de.mm20.launcher2.appshortcuts.AppShortcutKt.throwIllegalArgumentException(AppShortcut.kt:3)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:182)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.measure-BRTryo0(LayoutNodeLayoutDelegate.kt:99)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:56)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:15)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:819)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:21)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:74)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:50)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:189)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:9)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
[78 lines truncated]
```

## Device info
APP.VERSION : 1.32.1<br>APP.VERSIONCODE : 2024072200<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Riyadh<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 7.1.0.253C185E1R2P4<br>VERSION.SDK.NUMBER : 33<br>BOARD : CRTN<br>BOOTLOADER : unknown<br>BRAND : HONOR<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : CRT-N31 7.1.0.253(C185E1R2P4)<br>FINGERPRINT : HONOR/CRT-NX1/HNCRT-M2:13/HONORCRT-N31/7.1.0.253C185E1R2P4:user/release-keys<br>HARDWARE : mt6833<br>HOST : cn-north1b-02f6b48f61717394975737-778f647f5d-hpmvb<br>ID : HONORCRT-N31<br>MANUFACTURER : HONOR<br>MODEL : CRT-NX1<br>PRODUCT : CRT-NX1<br>TAGS : release-keys<br>TIME : 1717395298000<br>TYPE : user

**Comment by exstntlmsnthrp** [comment]
I think this is another duplicate of #962, but not completely certain.

**Comment by MM2-0** [comment]
> I think this is another duplicate of #962, but not completely certain.

It"s not
