### ISSUE TITLE
Bug during use, when closing the Search unexpectedly

### ISSUE THREAD

**Issue by LeonelRFF** [MM2-0/Kvaesitso#1010]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.NullPointerException
	at androidx.compose.foundation.text.input.internal.LegacyCursorAnchorInfoController.updateCursorAnchorInfo(LegacyCursorAnchorInfoController.android.kt:29)
	at androidx.compose.foundation.text.input.internal.AndroidLegacyPlatformTextInputServiceAdapter.updateTextLayoutResult(LegacyPlatformTextInputServiceAdapter.android.kt:31)
	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$onPositionedModifier$1$1.invoke(CoreTextField.kt:197)
	at androidx.compose.ui.layout.OnGloballyPositionedNode.onGloballyPositioned(OnGloballyPositionedModifier.kt:3)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:66)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks(MeasureAndLayoutDelegate.kt:73)
	at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:44)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:15)
[50 lines truncated]
```

## Device info
APP.VERSION : 1.32.1<br>APP.VERSIONCODE : 2024072200<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : America/Argentina/Buenos_Aires<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : S.18b42c3-bd0a-110b46<br>VERSION.SDK.NUMBER : 34<br>BOARD : bengal<br>BOOTLOADER : unknown<br>BRAND : OPPO<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : CPH2363_14.0.0.710(EX01)<br>FINGERPRINT : OPPO/CPH2363/OP533FL1:14/TP1A.220905.001/S.18b42c3-bd0a-110b46:user/release-keys<br>HARDWARE : qcom<br>HOST : dg02-pool06-kvm20<br>ID : TP1A.220905.001<br>MANUFACTURER : OPPO<br>MODEL : CPH2363<br>PRODUCT : CPH2363<br>TAGS : release-keys<br>TIME : 1719239570000<br>TYPE : user

**Comment by aptech73** [comment]
It's a Compose error: https://issuetracker.google.com/issues/313010266
