### ISSUE TITLE
kvaesi to error

### ISSUE THREAD

**Issue by frantik23** [MM2-0/Kvaesitso#1045]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.SharedLauncherActivity}
	at androidx.core.app.TaskStackBuilder.addParentStack(TaskStackBuilder.java:39)
	at androidx.navigation.NavDeepLinkBuilder.createTaskStackBuilder(NavDeepLinkBuilder.kt:160)
	at androidx.navigation.NavController.navigateUp(NavController.kt:368)
	at de.mm20.launcher2.ui.component.preferences.PreferenceScreenKt$PreferenceScreen$3$1$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:5)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:81)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:100)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:32)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:104)
[61 lines truncated]
```

## Device info
APP.VERSION : 1.32.2<br>APP.VERSIONCODE : 2024072400<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Copenhagen<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : eng.compil.20240816.154342<br>VERSION.SDK.NUMBER : 34<br>BOARD : k6989v1_64<br>BOOTLOADER : unknown<br>BRAND : vivo<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007 release-keys<br>FINGERPRINT : vivo/V2309/V2309:14/UP1A.231005.007/compiler08161540:user/release-keys<br>HARDWARE : mt6989<br>HOST : comdg01150030<br>ID : UP1A.231005.007<br>MANUFACTURER : vivo<br>MODEL : V2309<br>PRODUCT : V2309<br>TAGS : release-keys<br>TIME : 1723794017000<br>TYPE : user

**Comment by MM2-0** [comment]
I think this has been fixed in 1.33.0 or something
