### ISSUE TITLE
Crash when typing in search bar

### ISSUE THREAD

**Issue by summoner001** [MM2-0/Kvaesitso#1048]
## Description

Try to typing in the searchbar for searching.

## Strack trace

```
java.lang.AbstractMethodError: abstract method "void android.location.LocationListener.onProviderDisabled(java.lang.String)"
	at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:384)
	at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:300)
	at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:316)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6717)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

```

## Device info
APP.VERSION : 1.33.0<br>APP.VERSIONCODE : 2024081700<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Budapest<br>VERSION.RELEASE : 9<br>VERSION.INCREMENTAL : 1565092464<br>VERSION.SDK.NUMBER : 28<br>BOARD : CUBOT<br>BOOTLOADER : unknown<br>BRAND : CUBOT<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : CUBOT_QUEST_V14_20200820<br>FINGERPRINT : CUBOT/QUEST_EEA/QUEST:9/P00610/1565092464:user/release-keys<br>HARDWARE : MT6762<br>HOST : 80-30<br>ID : P00610<br>MANUFACTURER : CUBOT<br>MODEL : QUEST<br>PRODUCT : QUEST_EEA<br>TAGS : release-keys<br>TIME : 1597907371000<br>TYPE : user

**Comment by summoner001** [comment]
If I turn off: „Search on OpenStreetMap” // Settings > Search > Locations > OpenStreetMap
The search is working.
