### ISSUE TITLE
Memory Leak / OutOfMemoryError

### ISSUE THREAD

**Issue by ali-n-code** [MM2-0/Kvaesitso#1059]
## Description

*Please provide as many information about the crash as possible 
Phone was getting very slow for a few hours - memory leak?

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 2173232 free bytes and 2122KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.getMatrix-sQKQjiQ(GraphicsLayerOwnerLayer.android.kt:55)
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.mapBounds(GraphicsLayerOwnerLayer.android.kt:23)
	at androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release(NodeCoordinator.kt:74)
	at androidx.compose.ui.node.NodeCoordinator.localBoundingBoxOf(NodeCoordinator.kt:79)
	at androidx.compose.ui.layout.LayoutCoordinatesKt.boundsInWindow(LayoutCoordinates.kt:31)
	at androidx.compose.ui.semantics.SemanticsNode.getBoundsInWindow(SemanticsNode.kt:19)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.subtreeSortedByGeometryGrouping(AndroidComposeViewAccessibilityDelegateCompat.android.kt:60)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.geometryDepthFirstSearch(AndroidComposeViewAccessibilityDelegateCompat.android.kt:56)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.subtreeSortedByGeometryGrouping(AndroidComposeViewAccessibilityDelegateCompat.android.kt:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.geometryDepthFirstSearch(AndroidComposeViewAccessibilityDelegateCompat.android.kt:56)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.subtreeSortedByGeometryGrouping(AndroidComposeViewAccessibilityDelegateCompat.android.kt:30)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.geometryDepthFirstSearch(AndroidComposeViewAccessibilityDelegateCompat.android.kt:56)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.geometryDepthFirstSearch(AndroidComposeViewAccessibilityDelegateCompat.android.kt:80)
	at androidx.compose.ui.platform.AndroidComposeViewAccessibilityDelegateCompat.subtreeSortedByGeometryGrouping(AndroidComposeViewAccessibilityDelegateCompat.android.kt:30)
[14 lines truncated]
```

## Device info
APP.VERSION : 1.32.1<br>APP.VERSIONCODE : 2024072200<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : Pacific/Auckland<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : F936BXXS5EXBF<br>VERSION.SDK.NUMBER : 34<br>BOARD : taro<br>BOOTLOADER : F936BXXS5EXBF<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.F936BXXS5EXBF<br>FINGERPRINT : samsung/q4qxxx/q4q:14/UP1A.231005.007/F936BXXS5EXBF:user/release-keys<br>HARDWARE : qcom<br>HOST : 21DK7A24<br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-F936B<br>PRODUCT : q4qxxx<br>TAGS : release-keys<br>TIME : 1709517391000<br>TYPE : user

**Comment by MM2-0** [comment]
No new reports in half a year, I assume this is fixed
