### ISSUE TITLE
App crashed while clicking the pause work apps option

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [MM2-0/Kvaesitso#1063]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: User 999 is not a profile
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.os.IUserManager$Stub$Proxy.requestQuietModeEnabled(IUserManager.java:3529)
	at android.os.UserManager.requestQuietModeEnabled(UserManager.java:5214)
	at android.os.UserManager.requestQuietModeEnabled(UserManager.java:5199)
	at android.os.UserManager.requestQuietModeEnabled(UserManager.java:5166)
	at de.mm20.launcher2.profiles.ProfileManager$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:2)
	at de.mm20.launcher2.ui.launcher.search.SearchColumnKt$SearchColumn$1$$ExternalSyntheticLambda15.invoke(R8$$SyntheticClass:46)
	at de.mm20.launcher2.ui.launcher.search.apps.AppResultsKt$AppResults$1$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:20)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
[70 lines truncated]
```

## Device info
APP.VERSION : 1.32.2-20240816-nightly<br>APP.VERSIONCODE : 2024081600<br>APP.SIGNATURE : wVhv3DbjVNC+HXuwkkmtXrdxWY8=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Calcutta<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 2406280430<br>VERSION.SDK.NUMBER : 34<br>BOARD : taro<br>BOOTLOADER : 00979.4-WAIPIO-1<br>BRAND : Nothing<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : U2.6-240628-0430<br>FINGERPRINT : Nothing/PongIND/Pong:14/UP1A.231005.007/2406280430:user/release-keys<br>HARDWARE : qcom<br>HOST : NTSV-J900XHX2<br>ID : UP1A.231005.007<br>MANUFACTURER : Nothing<br>MODEL : AIN065<br>PRODUCT : PongIND<br>TAGS : release-keys<br>TIME : 1719520201000<br>TYPE : user

**Comment by MM2-0** [comment]
@Bhardwaj10Ankit please do not download whatever the deleted comment was linking (in case you still have the link in your emails). It's malware and it apparently tries to steal your Github account.
