### ISSUE TITLE
Porque mes sale eso 

### ISSUE THREAD

**Issue by JKJ1000** [MM2-0/Kvaesitso#1080]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.SharedLauncherActivity}
	at androidx.core.app.TaskStackBuilder.addParentStack(TaskStackBuilder.java:39)
	at androidx.navigation.NavDeepLinkBuilder.createTaskStackBuilder(NavDeepLinkBuilder.kt:160)
	at androidx.navigation.NavController.navigateUp(NavController.kt:368)
	at de.mm20.launcher2.ui.component.preferences.PreferenceScreenKt$PreferenceScreen$3$1$$ExternalSyntheticLambda0.invoke(R8$$SyntheticClass:5)
	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:81)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:100)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:33)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:32)
	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:104)
[60 lines truncated]
```

## Device info
APP.VERSION : 1.32.2<br>APP.VERSIONCODE : 2024072400<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : America/Caracas<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : GL-20240813V548<br>VERSION.SDK.NUMBER : 31<br>BOARD : Infinix-X669<br>BOOTLOADER : unknown<br>BRAND : Infinix<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : X669-F065FGHIJK-S-GL-20240813V548<br>FINGERPRINT : Infinix/X669-GL/Infinix-X669:12/SP1A.210812.016/GL-20240813V548:user/release-keys<br>HARDWARE : X669<br>HOST : buildsrv-cq10<br>ID : SP1A.210812.016<br>MANUFACTURER : INFINIX<br>MODEL : Infinix X669<br>PRODUCT : X669-GL<br>TAGS : release-keys<br>TIME : 1723555599000<br>TYPE : user

**Comment by MM2-0** [comment]
Outdated version, fixed in 1.33
