### ISSUE TITLE
Weather select City crash

### ISSUE THREAD

**Issue by Tealk** [MM2-0/Kvaesitso#110]
I get this Crash if i try to set up a city in the weather widget using DWD

```
java.io.IOException: no result
	at android.location.Geocoder$GeocodeListener.getResults(Geocoder.java:246)
	at android.location.Geocoder.getFromLocationName(Geocoder.java:215)
	at android.location.Geocoder.getFromLocationName(Geocoder.java:164)
	at de.mm20.launcher2.weather.LatLonWeatherProvider$lookupLocation$locations$1.invokeSuspend(LatLonWeatherProvider.kt:24)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@7c6c306, androidx.compose.runtime.BroadcastFrameClock@bb10dc7, StandaloneCoroutine{Cancelling}@b7faff4, AndroidUiDispatcher@7b2731d]
```

```
APP.VERSION : 1.12.0-20220613
APP.VERSIONCODE : 2022061300
APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=
LAUNCHER.APP : de.mm20.launcher2.release
TIMEZONE : Europe/Berlin
VERSION.RELEASE : 12
VERSION.INCREMENTAL : 22306002
VERSION.SDK.NUMBER : 32
BOARD : oriole
BOOTLOADER : slider-1.2-8318357
BRAND : google
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : SQ3A.220605.009.A1.22306002
FINGERPRINT : google/oriole/oriole:12/SQ3A.220605.009.B1/8650216:user/release-keys
HARDWARE : oriole
HOST : aosp-build
ID : SQ3A.220605.009.A1
MANUFACTURER : Google
MODEL : Pixel 6
PRODUCT : oriole
TAGS : release-keys
TIME : 1654662802000
TYPE : user
```

**Comment by MM2-0** [comment]
Thanks for the report. Do you, by any chance use a custom rom without Google Play services? The Geocoder might not be available in that case (though it shouldn't crash, of course). You can try to use the OpenWeatherMap or HERE provider, both use their own geocoder so they should work regardless of the presence of Play services.

**Comment by Tealk** [comment]
I use CalyxOS with MicroG

**Comment by MM2-0** [comment]
Fixed in 5bace7d

Starting with the next version, you'll be able to manually set Met.No and DWD locations using the following syntax: `[lat] [lon] [location name]` even if no geocoder is available on the device.

**Comment by Tealk** [comment]
Can't wait, thank you very much.

**Comment by Tealk** [comment]
Syntax: [lat] [lon] works great, thanks
