### ISSUE TITLE
Background Crash Report While Browsing Settings

### ISSUE THREAD

**Issue by R-Bose** [MM2-0/Kvaesitso#1105]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1225921436, result=0, data=Intent { (has extras) }} to activity {de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.LauncherActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: X.4hR
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5946)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5985)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
[27 lines truncated]
```

## Device info
APP.VERSION : 1.33.1<br>APP.VERSIONCODE : 2024090300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Oslo<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : M315FXXS4CXB1<br>VERSION.SDK.NUMBER : 31<br>BOARD : exynos9611<br>BOOTLOADER : M315FXXS4CXB1<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : SP1A.210812.016.M315FXXS4CXB1<br>FINGERPRINT : samsung/m31nnxx/m31:12/SP1A.210812.016/M315FXXS4CXB1:user/release-keys<br>HARDWARE : exynos9611<br>HOST : 21DKGB22<br>ID : SP1A.210812.016<br>MANUFACTURER : samsung<br>MODEL : SM-M315F<br>PRODUCT : m31nnxx<br>TAGS : release-keys<br>TIME : 1707730318000<br>TYPE : user

**Comment by summoner001** [comment]
Try to turn off: „Search on OpenStreetMap” // Settings > Search > Locations > OpenStreetMap
Its work for me.

**Comment by R-Bose** [comment]
> Try to turn off: „Search on OpenStreetMap” // Settings > Search > Locations > OpenStreetMap Its work for me.

It's been off, I never turned it on. Also I can't really replicate this issue, this crash report just popped up in my notifications randomly when I first saw it.
