### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by m0tholith** [MM2-0/Kvaesitso#1145]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*
After some time from loading and usage, I just swiped down to get to the search menu and then this crash happened. It happened a moment after the menu appeared so it might have to do with the search filter above the keyboard.

## Stack trace

```
java.lang.IllegalArgumentException: Error: Uninitialized LayoutCoordinates. Please make sure when using the SharedTransitionScope composable function, the modifier passed to the child content is being used, or use SharedTransitionLayout instead.
	at androidx.compose.animation.SharedBoundsNode$measure$1.invoke(SharedContentNode.kt:75)
	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(LookaheadDelegate.kt:7)
	at androidx.compose.ui.node.LookaheadDelegate.placeChildren(LookaheadDelegate.kt:5)
	at androidx.compose.ui.node.LookaheadDelegate.placeAt-f8xVGno(LookaheadDelegate.kt:9)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:15)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate$placeSelf$2.invoke(LayoutNodeLayoutDelegate.kt:60)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:114)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:52)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:134)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.placeSelf-MLgxB_4$1(LayoutNodeLayoutDelegate.kt:109)
	at androidx.compose.ui.node.LayoutNode.lookaheadReplace$ui_release(LayoutNode.kt:43)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:41)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:44)
[17 lines truncated]
```

## Device info
APP.VERSION : 1.33.1-20241123-nightly<br>APP.VERSIONCODE : 2024112300<br>APP.SIGNATURE : wVhv3DbjVNC+HXuwkkmtXrdxWY8=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Amman<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : c70c1f5cf1<br>VERSION.SDK.NUMBER : 34<br>BOARD : atoll<br>BOOTLOADER : A525FXXS6DWK1<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : lineage_a52q-userdebug 14 AP2A.240905.003 c70c1f5cf1<br>FINGERPRINT : samsung/a52qnsxx/a52q:11/RP1A.200720.012/A525FXXS7FXE2:user/release-keys<br>HARDWARE : qcom<br>HOST : 7cc8de0f1daf<br>ID : AP2A.240905.003<br>MANUFACTURER : samsung<br>MODEL : SM-A525F<br>PRODUCT : a52qnsxx<br>TAGS : release-keys<br>TIME : 1728864560000<br>TYPE : userdebug

**Comment by MM2-0** [comment]
Oh no, not this again. Alright, time to revert this: cd803974de86f4bf94b1d39e4d95687b80a721d9
