### ISSUE TITLE
Sudden crash

### ISSUE THREAD

**Issue by glemco** [MM2-0/Kvaesitso#115]
## Description

I didn't do anything particular to get there, just going back to the home caused this crash and now I cannot use the launcher anymore. It blinks or crashes, force stopping or rebooting didn't help.
I don't have any custom widget, let me know if you need additional information.

## Strack trace

```
java.lang.NullPointerException: cur.getString(1).takeUnl…      ?: cur.getString(2) must not be null
	at de.mm20.launcher2.calendar.CalendarRepositoryImpl$queryCalendarEvents$results$1.invokeSuspend(CalendarRepository.kt:113)
	at de.mm20.launcher2.calendar.CalendarRepositoryImpl$queryCalendarEvents$results$1.invoke(Unknown Source:8)
	at de.mm20.launcher2.calendar.CalendarRepositoryImpl$queryCalendarEvents$results$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.mm20.launcher2.calendar.CalendarRepositoryImpl.queryCalendarEvents(CalendarRepository.kt:68)
	at de.mm20.launcher2.calendar.CalendarRepositoryImpl.access$queryCalendarEvents(CalendarRepository.kt:27)
	at de.mm20.launcher2.calendar.CalendarRepositoryImpl$getUpcomingEvents$1$1$2$events$1.invokeSuspend(CalendarRepository.kt:155)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
[5 lines truncated]
```

## Device info
APP.VERSION : 1.12.0-20220613<br>APP.VERSIONCODE : 2022061300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : eng.androi.20220226.162719<br>VERSION.SDK.NUMBER : 31<br>BOARD : kona<br>BOOTLOADER : unknown<br>BRAND : OnePlus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : aosp_lemonkebab-userdebug 12 SQ1D.220205.003 eng.androi.20220226.162719 test-keys<br>FINGERPRINT : OnePlus/aosp_lemonkebab/lemonkebab:12/SQ1D.220205.003/android-build02261624:userdebug/test-keys<br>HARDWARE : qcom<br>HOST : aospextended-build<br>ID : SQ1D.220205.003<br>MANUFACTURER : OnePlus<br>MODEL : KB2003<br>PRODUCT : aosp_lemonkebab<br>TAGS : release-keys<br>TIME : 1645892691000<br>TYPE : userdebug

**Comment by glemco** [comment]
Great, thanks!
