### ISSUE TITLE
NullPointerException in IconService.resolveCustomIcon

### ISSUE THREAD

**Issue by Termimad** [MM2-0/Kvaesitso#1181]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Stack trace

```
java.lang.NullPointerException
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invokeSuspend(IconService.kt:214)
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invoke(IconService.kt:28)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:49)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:252)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invoke(Combine.kt:13)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:16)
	at kotlinx.coroutines.flow.internal.CombineKt.combineInternal(Combine.kt:21)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:78)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invoke(Merge.kt:22)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:35)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:37)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:36)
[19 lines truncated]
```

## Device info
APP.VERSION : 1.34.0<br>APP.VERSIONCODE : 2024120500<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : a67b9-b3a31<br>VERSION.SDK.NUMBER : 31<br>BOARD : caprip<br>BOOTLOADER : MBM-3.0-caprip_retail-cc5bf3e3081-240203<br>BRAND : motorola<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : S0RCS32.41-10-19-23<br>FINGERPRINT : motorola/caprip_retailen/caprip:12/S0RCS32.41-10-19-23/a67b9-b3a31:user/release-keys<br>HARDWARE : qcom<br>HOST : ilclbld155<br>ID : S0RCS32.41-10-19-23<br>MANUFACTURER : motorola<br>MODEL : moto g(30)<br>PRODUCT : caprip_retailen<br>TAGS : release-keys<br>TIME : 1706976504000<br>TYPE : user

**Comment by MM2-0** [comment]
Can you provide more details? Can you reproduce it or does it happen randomly? What kind of custom icons have you assigned?

**Comment by chefexperte** [comment]
I have a similar (or same) error:

## Stack trace

```
java.lang.NullPointerException
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invokeSuspend(IconService.kt:214)
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invoke(IconService.kt:28)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:49)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:252)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invoke(Combine.kt:13)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:16)
	at kotlinx.coroutines.flow.internal.CombineKt.combineInternal(Combine.kt:21)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:78)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invoke(Merge.kt:22)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:35)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:37)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:36)
[21 lines truncated]
```

## Device info
APP.VERSION : 1.34.0-fdroid<br>APP.VERSIONCODE : 2024120500<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 15<br>VERSION.INCREMENTAL : 2024121200<br>VERSION.SDK.NUMBER : 35<br>BOARD : panther<br>BOOTLOADER : cloudripper-15.1-12292122<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : 2024121200<br>FINGERPRINT : google/panther/panther:15/AP4A.241205.013/2024121200:user/release-keys<br>HARDWARE : panther<br>HOST : grapheneos<br>ID : AP4A.241205.013<br>MANUFACTURER : Google<br>MODEL : Pixel 7<br>PRODUCT : panther<br>TAGS : release-keys<br>TIME : 1734016865000<br>TYPE : user


It happens randomly when I'm going back to the homescreen, I don't know how to reproduce it, it seems really random.

**Comment by 2br-2b** [comment]
I seem to be having the same issue. Here's my full trace.

The problem is that every time the launcher crashes, Android disables its accessibility service. In addition, I have to reselect it as the launcher. While this is definitely my favorite launcher, this bug is a deal breaker for me

## Stack trace

```
java.lang.NullPointerException
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invokeSuspend(IconService.kt:214)
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invoke(IconService.kt:28)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:49)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:252)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invoke(Combine.kt:13)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:16)
	at kotlinx.coroutines.flow.internal.CombineKt.combineInternal(Combine.kt:21)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:79)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invoke(Merge.kt:22)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:35)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:37)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:36)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:105)
	at de.mm20.launcher2.data.customattrs.CustomAttributesRepositoryImpl$getCustomIcon$$inlined$map$1$2.emit(Emitters.kt:69)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:17)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:128)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at android.os.Handler.handleCallback(Handler.java:991)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8bb44dc, Dispatchers.Main.immediate]
```

## Device info
APP.VERSION : 1.34.1-fdroid<br>APP.VERSIONCODE : 2024122400<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : America/New_York<br>VERSION.RELEASE : 15<br>VERSION.INCREMENTAL : 2025011500<br>VERSION.SDK.NUMBER : 35<br>BOARD : lynx<br>BOOTLOADER : lynx-15.1-12292122<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : 2025011500<br>FINGERPRINT : google/lynx/lynx:15/AP4A.250105.002/2025011500:user/release-keys<br>HARDWARE : lynx<br>HOST : grapheneos<br>ID : AP4A.250105.002<br>MANUFACTURER : Google<br>MODEL : Pixel 7a<br>PRODUCT : lynx<br>TAGS : release-keys<br>TIME : 1736927777000<br>TYPE : user

**Comment by Kondor777200** [comment]
Looks like i am encountering the same issue..

## Stack trace

```
java.lang.NullPointerException
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invokeSuspend(IconService.kt:214)
	at de.mm20.launcher2.icons.IconService$resolveCustomIcon$1.invoke(IconService.kt:28)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:49)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:252)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invoke(Combine.kt:13)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:16)
	at kotlinx.coroutines.flow.internal.CombineKt.combineInternal(Combine.kt:21)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invokeSuspend(Merge.kt:79)
	at de.mm20.launcher2.icons.IconService$getIcon$$inlined$flatMapLatest$1.invoke(Merge.kt:22)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:35)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt:13)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:37)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:36)
[21 lines truncated]
```

## Device info
APP.VERSION : 1.34.1<br>APP.VERSIONCODE : 2024122400<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : */*e<br>VERSION.RELEASE : 15<br>VERSION.INCREMENTAL : 2025021100<br>VERSION.SDK.NUMBER : 35<br>BOARD : lynx<br>BOOTLOADER : lynx-15.1-12292122<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : 2025021100<br>FINGERPRINT : google/lynx/lynx:15/AP4A.250205.002/2025021100:user/release-keys<br>HARDWARE : lynx<br>HOST : r-0123456789abcdef-0123<br>ID : AP4A.250205.002<br>MANUFACTURER : Google<br>MODEL : Pixel 7a<br>PRODUCT : lynx<br>TAGS : release-keys<br>TIME : 1739278608000<br>TYPE : user

**Comment by 2br-2b** [comment]
Looking at what appears to be the lines (assuming the stack grace hasn't changed), maybe it means a custom icon provider was available and is now removed? Like maybe there was an icon pack that I assigned an icon from, then I uninstalled the icon pack?

On the other hand, it'll crash, but then reloading it causes the launcher to work. The problem is that this happens constantly, so reloading the app (and being forced to choose it again as the primary launcher) is very annoying.

https://github.com/MM2-0/Kvaesitso/blob/main/services%2Ficons%2Fsrc%2Fmain%2Fjava%2Fde%2Fmm20%2Flauncher2%2Ficons%2FIconService.kt#L214-L217 

Regardless, maybe this should be in a try/catch loop to prevent an icon issue from crashing the app.
