### ISSUE TITLE
Default launcher app

### ISSUE THREAD

**Issue by RadioactivePlays** [MM2-0/Kvaesitso#151]
I am using Kvaesitso for like 6 months now. This week everytime i press the phone home button it ask me to choose a default home app again and again. I dont know if it's an bug on Kvaesitso or on my system.
![Screenshot_20220823-204806](https://user-images.githubusercontent.com/19830027/186310964-cf493e6d-9ce1-4771-af3b-c0319a9e7913.png)

**Comment by MM2-0** [comment]
Are you on the latest version (1.14.3)? There's two issues in 1.14.2 which might result in the behavior you described:

1. There is a bug that leads to frequent crashes
2. The crash notifications are broken

If the launcher app crashes frequently, the system will reset the default launcher app.

So please check if you are on the latest version and if there are any crashes (settings > debug > crash reporter)

**Comment by RadioactivePlays** [comment]
in fact i was using a old version (1.14.1) then i updated to the last one but it keeps happening. There are a lot of crash logs, most of then related to weathers provider service. Here is the last one:
`java.net.SocketTimeoutException: SSL handshake timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:30)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:30)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:19)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:16)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:33)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:16)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:28)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:16)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:35)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:16)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:23)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:12)
	at de.mm20.launcher2.weather.metno.MetNoProvider.loadWeatherData$weather_release(MetNoProvider.kt:20)
	at de.mm20.launcher2.weather.metno.MetNoProvider.loadWeatherData$weather_release(MetNoProvider.kt:1)
	at de.mm20.launcher2.weather.WeatherProvider.fetchNewWeatherData(WeatherProvider.kt:13)
	at de.mm20.launcher2.weather.WeatherUpdateWorker.doWork(WeatherRepository.kt:21)
	at androidx.work.CoroutineWorker$startWork$1.invokeSuspend(CoroutineWorker.kt:4)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
`
