### ISSUE TITLE
Crash caused by Google Drive connection

### ISSUE THREAD

**Issue by eengnr** [MM2-0/Kvaesitso#166]
## Description

Searching files in Google Drive worked fine, but suddenly Kvaesitso crashes when I search for anything.
Disabling the search in Google Drive stopped the crashes.
It's also not possible to disconnect Google Drive, when I try it, then Kvaesitso crashes as well.

## Strack trace

```
java.io.StreamCorruptedException: invalid stream header: 00000000
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:863)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:354)
	at com.google.api.client.util.IOUtils.deserialize(IOUtils.java:2)
	at com.google.api.client.util.store.FileDataStoreFactory$FileDataStore.<init>(FileDataStoreFactory.java:7)
	at com.google.api.client.util.store.FileDataStoreFactory.createDataStore(Unknown Source:4)
	at com.google.api.client.util.store.AbstractDataStoreFactory.getDataStore(AbstractDataStoreFactory.java:6)
	at de.mm20.launcher2.gservices.GoogleApiHelper.getAuthFlow(GoogleApiHelper.kt:9)
	at de.mm20.launcher2.gservices.GoogleApiHelper.getRequestInitializer(GoogleApiHelper.kt:5)
	at de.mm20.launcher2.gservices.GoogleApiHelper.queryGDriveFiles(GoogleApiHelper.kt:4)
	at de.mm20.launcher2.files.providers.GDriveFileProvider.search(GDriveFileProvider.kt:5)
	at de.mm20.launcher2.files.FileRepositoryImpl$search$1$1.invokeSuspend(FilesRepository.kt:9)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:14)
[2 lines truncated]
```

## Device info
APP.VERSION : 1.15.0-20220907<br>APP.VERSIONCODE : 2022090700<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 8927612<br>VERSION.SDK.NUMBER : 33<br>BOARD : oriole<br>BOOTLOADER : slider-1.2-8739948<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : TP1A.220905.004<br>FINGERPRINT : google/oriole/oriole:13/TP1A.220905.004/8927612:user/release-keys<br>HARDWARE : oriole<br>HOST : abfarm-release-rbe-64-00030<br>ID : TP1A.220905.004<br>MANUFACTURER : Google<br>MODEL : Pixel 6<br>PRODUCT : oriole<br>TAGS : release-keys<br>TIME : 1660096525000<br>TYPE : user

**Comment by MM2-0** [comment]
Could you clear the app's data and try again? I need to make sure that is is a random one-time error (file got corrupted for some reason) and not a general issue on Android 13.

You can use the backup / restore functionality to keep (most of) your data

**Comment by eengnr** [comment]
I deleted the app data and re-connected Google Drive -> no crash observed, when searching (for anything or a file on Google Drive)
Then I restored the backup, activated searching in Google Drive again -> still no crash observed

So this doesn't seem to be a general issue.
I'll keep it active now, let's see if it happens again.

**Comment by MM2-0** [comment]
Thanks. I'll improve the error handling in case of a corrupted Google data store file so that the launcher no longer crashes if that happens.
