### ISSUE TITLE
Repeated crashes when playing media

### ISSUE THREAD

**Issue by eengnr** [MM2-0/Kvaesitso#168]
## Description

This crash happens repeatedly when playing media (e.g. RadioDroid) as soon as Kvaesitso tries to show the media control. Probably some information (title? artist?) is missing?

## Strack trace

```
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:499)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:199)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:186)
	at android.text.SpannableString.setSpan(SpannableString.java:60)
	at androidx.compose.ui.text.platform.extensions.SpannableExtensions_androidKt.setSpan(Unknown Source:12)
	at androidx.compose.ui.text.AndroidParagraph.<init>(AndroidParagraph.android.kt:20)
	at androidx.compose.ui.text.MultiParagraph.<init>(MultiParagraph.kt:20)
	at androidx.compose.foundation.text.TextDelegate.layout-NN6Ew-U(TextDelegate.kt:68)
	at androidx.compose.foundation.text.TextController$measurePolicy$1.measure-3p2s80s(CoreText.kt:6)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:11)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:2)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:5)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1)
[115 lines truncated]
```

## Device info
APP.VERSION : 1.15.0-20220907<br>APP.VERSIONCODE : 2022090700<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 8927612<br>VERSION.SDK.NUMBER : 33<br>BOARD : oriole<br>BOOTLOADER : slider-1.2-8739948<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : TP1A.220905.004<br>FINGERPRINT : google/oriole/oriole:13/TP1A.220905.004/8927612:user/release-keys<br>HARDWARE : oriole<br>HOST : abfarm-release-rbe-64-00030<br>ID : TP1A.220905.004<br>MANUFACTURER : Google<br>MODEL : Pixel 6<br>PRODUCT : oriole<br>TAGS : release-keys<br>TIME : 1660096525000<br>TYPE : user

**Comment by MM2-0** [comment]
I think the underlying bug in Jetpack Compose has been fixed, please check if the issue still occurs in 1.16.0

**Comment by eengnr** [comment]
Looks ok, no more crashes so far!
