### ISSUE TITLE
Kvaesitso crashes when searching website

### ISSUE THREAD

**Issue by HerrHellmus** [MM2-0/Kvaesitso#18]
Found another issue. When I search for a website, e.g. google.com, the launcher crashes.

’’’
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:742)
at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:749)
at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:94)
at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:152)
at android.graphics.Canvas.drawBitmap(Canvas.java:1605)
at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:560)
at de.mm20.launcher2.ui.legacy.view.LauncherIconView.onDraw(LauncherIconView.kt:402)
at android.view.View.draw(View.java:23893)
at android.view.View.buildDrawingCacheImpl(View.java:23159)
at android.view.View.buildDrawingCache(View.java:23019)
at android.view.View.updateDisplayListIfDirty(View.java:22730)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.updateDisplayListIfDirty(View.java:22748)
at android.view.View.draw(View.java:23623)
at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
at android.view.View.draw(View.java:23896)
at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:2073)
at android.view.View.updateDisplayListIfDirty(View.java:22762)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:5339)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:5311)
at android.view.View.updateDisplayListIfDirty(View.java:22709)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:5306)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5014)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4107)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2832)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10332)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1063)
at android.view.Choreographer.doCallbacks(Choreographer.java:845)
at android.view.Choreographer.doFrame(Choreographer.java:780)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8633)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
’’’

**Comment by BrightDV** [comment]
Same issue for me for Google.com
However, I tried with other websites such as duckduckgo, brave and github but the launcher didn't thrown any exception

**Comment by HerrHellmus** [comment]
Hey, you're right! I also tried it with my personal homepage, which is just an html page with a jpeg. That made it crash as well.

**Comment by MM2-0** [comment]
Fixed in be2b147
