### ISSUE TITLE
cierre

### ISSUE THREAD

**Issue by facucb** [MM2-0/Kvaesitso#187]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: Key app://com.aurora.store:com.aurora.store.view.ui.onboarding.OnboardingActivity was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:168)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:38)
	at androidx.compose.foundation.lazy.grid.LazyMeasuredItemProvider.getAndMeasure-ednRnyU(LazyMeasuredItemProvider.kt:9)
	at androidx.compose.foundation.lazy.grid.LazyMeasuredLineProvider.getAndMeasure-bKFJvoY(LazyMeasuredLineProvider.kt:53)
	at androidx.compose.foundation.lazy.grid.LazyGridKt$rememberLazyGridMeasurePolicy$1$1.invoke(LazyGrid.kt:794)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$1$2$1.invoke(LazyLayout.kt:26)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:63)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:44)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:6)
	at androidx.compose.ui.node.BackwardsCompatNode.measure-3p2s80s(BackwardsCompatNode.kt:15)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:11)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:9)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:64)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:7)
[98 lines truncated]
```

## Device info
APP.VERSION : 1.17.0-20220928<br>APP.VERSIONCODE : 2022092800<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Madrid<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : eng.root.20221014.022301<br>VERSION.SDK.NUMBER : 32<br>BOARD : sm6150<br>BOOTLOADER : unknown<br>BRAND : POCO<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : lineage_surya-userdebug 12 SQ3A.220705.004 eng.root.20221014.022301 dev-keys<br>FINGERPRINT : POCO/surya_eea/surya:11/RKQ1.200826.002/V12.5.8.0.RJGMIXM:user/release-keys<br>HARDWARE : qcom<br>HOST : b1fbab9ad11f<br>ID : SQ3A.220705.004<br>MANUFACTURER : Xiaomi<br>MODEL : M2007J20CG<br>PRODUCT : surya_global<br>TAGS : dev-keys<br>TIME : 1665714079000<br>TYPE : userdebug

**Comment by MM2-0** [comment]
Can you try Settings > Debug > Clean up database and see whether that fixes it?

**Comment by facucb** [comment]
It works perfectly. Thank you very much and good job
