### ISSUE TITLE
app crashes in settings menu 

### ISSUE THREAD

**Issue by mnisius** [MM2-0/Kvaesitso#195]
## Description

Launcher looks nice but crashes instantly when I open the settings menu. This is the stack trace. I'm on Android 12 (crdroid 8.10) 

## Strack trace

```
java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2432)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.stopListening(IAppWidgetService.java:792)
	at android.appwidget.AppWidgetHost.stopListening(AppWidgetHost.java:258)
	at de.mm20.launcher2.ui.launcher.widgets.WidgetColumnKt$WidgetColumn$1$1.invokeSuspend(WidgetColumn.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
[14 lines truncated]
```

## Device info
APP.VERSION : 1.18.0-20221022<br>APP.VERSIONCODE : 2022102200<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : com.android.launcher3<br>TIMEZONE : Europe/Madrid<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : 42<br>VERSION.SDK.NUMBER : 32<br>BOARD : sdm845<br>BOOTLOADER : unknown<br>BRAND : Xiaomi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : SQ3A.220705.004<br>FINGERPRINT : Xiaomi/beryllium/beryllium:10/QKQ1.190828.002/V12.0.3.0.QEJMIXM:user/release-keys<br>HARDWARE : qcom<br>HOST : android-build<br>ID : SQ3A.220705.004<br>MANUFACTURER : Xiaomi<br>MODEL : POCO F1<br>PRODUCT : beryllium<br>TAGS : release-keys<br>TIME : 1665956231000<br>TYPE : user

**Comment by hobias** [comment]
## Description

Probably the same issue here.

## Stack trace

```java.lang.NullPointerException:` Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2431)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.stopListening(IAppWidgetService.java:792)
	at android.appwidget.AppWidgetHost.stopListening(AppWidgetHost.java:258)
	at de.mm20.launcher2.ui.launcher.widgets.WidgetColumnKt$WidgetColumn$1$1.invokeSuspend(WidgetColumn.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7941)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@54162ec, androidx.compose.runtime.BroadcastFrameClock@78336b5, StandaloneCoroutine{Cancelling}@287a14a, AndroidUiDispatcher@2068bb]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.appwidget.AppWidgetServiceImpl$Host.getWidgetUids(AppWidgetServiceImpl.java:4170)
	at com.android.server.appwidget.AppWidgetServiceImpl.stopListening(AppWidgetServiceImpl.java:794)
	at com.android.internal.appwidget.IAppWidgetService$Stub.onTransact(IAppWidgetService.java:311)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at `android.os.Binder.execTransact(Binder.java:1143)```


## Device info
APP.VERSION : 1.20.0-20221222<br>APP.VERSIONCODE : 2022122200<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : com.nothing.launcher<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : 1654881925<br>VERSION.SDK.NUMBER : 31<br>BOARD : lahaina<br>BOOTLOADER : unknown<br>BRAND : Nothing<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : Spacewar-S1.0-220611-0125<br>FINGERPRINT : Nothing/SpacewarEEA/Spacewar:12/SKQ1.211230.001/1654881925:user/release-keys<br>HARDWARE : qcom<br>HOST : NT-BUILDER<br>ID : SKQ1.211230.001<br>MANUFACTURER : Nothing<br>MODEL : A063<br>PRODUCT : SpacewarEEA<br>TAGS : release-keys<br>TIME : 1654882822000<br>TYPE : user
