### ISSUE TITLE
Crash with "No virtual method addOnColorsChangedListener" exception

### ISSUE THREAD

**Issue by Occhioverde** [MM2-0/Kvaesitso#197]
As per the title, after the update to the latest (1.18.0) version, Kvæsitso started crashing every time I try to open it reporting the following error:

```
java.lang.NoSuchMethodError: No virtual method addOnColorsChangedListener(Landroid/app/WallpaperManager$OnColorsChangedListener;Landroid/os/Handler;)V in class Landroid/app/WallpaperManager; or its super classes (declaration of 'android.app.WallpaperManager' appears in /system/framework/framework.jar)
	at de.mm20.launcher2.ui.theme.WallpaperColorsKt$wallpaperColorsAsState$1$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at de.mm20.launcher2.ui.theme.WallpaperColorsKt$wallpaperColorsAsState$1.invoke(WallpaperColors.kt:35)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:5)
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:94)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:86)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:101)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:13)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:72)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:12)
	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:13)
	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:19)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:18)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:115)
	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:37)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:104)
	at android.view.View.dispatchAttachedToWindow(View.java:17558)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3332)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3339)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1799)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7292)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:721)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

Since the launcher crashes even when trying to open the crash report (the trace above has been extracted from `Internal Storage/Android/data/de.mm20.launcher2.release/files/crashReports`) I can't provide you with the device info that the app usually prints after a crash, but in case it can be useful to debug the problem the device on which I'm encountering the issue is a Huawei BAH2-W19 running Android 8.0.0.

For the sake of completeness, I installed the update on my Asus Zenfone 4 Max with the same OS version, but I can't seem to reproduce the error.

Thanks in advance for the help.

**Comment by MM2-0** [comment]
Ah, yes, sorry, this has already been fixed it in 98d12d30 but then I ~~was too lazy~~ “forgot” to release.
Here you go: https://github.com/MM2-0/Kvaesitso/releases/tag/v1.18.1
