### ISSUE TITLE
crash when i click backspace at search bar when empty

### ISSUE THREAD

**Issue by wofflez** [MM2-0/Kvaesitso#210]
## Description

Search bar is empty, but click back space, it will crash

## Strack trace

```
java.lang.IllegalArgumentException: offset(-1) is out of bounds [0, 0]
	at androidx.compose.ui.text.MultiParagraph.requireIndexInRangeInclusiveEnd(MultiParagraph.kt:54)
	at androidx.compose.ui.text.TextLayoutResult.getWordBoundary--jx7JFs(TextLayoutResult.kt:3)
	at androidx.compose.foundation.text.selection.BaseTextPreparedSelection.getPrevWordOffset(TextPreparedSelection.kt:19)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2$5.invoke(TextFieldKeyInput.kt:25)
	at androidx.compose.foundation.text.selection.TextFieldPreparedSelection.deleteIfSelectedOr(TextPreparedSelection.kt:14)
	at androidx.compose.foundation.text.TextFieldKeyInput$process$2.invoke(TextFieldKeyInput.kt:545)
	at androidx.compose.foundation.text.TextFieldKeyInputKt$textFieldKeyInput$2$1.invoke(TextFieldKeyInput.kt:152)
	at androidx.compose.ui.input.key.KeyInputModifier.propagateKeyEvent-ZmokQxo(KeyInputModifier.kt:15)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchKeyEvent(AndroidComposeView.android.kt:126)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1979)
[35 lines truncated]
```

## Device info
APP.VERSION : 1.18.1-20221026<br>APP.VERSIONCODE : 2022102600<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Brunei<br>VERSION.RELEASE : 10<br>VERSION.INCREMENTAL : 10.1.0.149C636<br>VERSION.SDK.NUMBER : 29<br>BOARD : ELE<br>BOOTLOADER : unknown<br>BRAND : HUAWEI<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : ELE-L29 10.1.0.149(C636E7R3P4)<br>FINGERPRINT : HUAWEI/ELE-L29/HWELE:10/HUAWEIELE-L29/10.1.0.149C636:user/release-keys<br>HARDWARE : kirin980<br>HOST : cn-central-1b-610a851301596192457257-834832025-jjkd7<br>ID : HUAWEIELE-L29<br>MANUFACTURER : HUAWEI<br>MODEL : ELE-L29<br>PRODUCT : ELE-L29<br>TAGS : release-keys<br>TIME : 1596196152000<br>TYPE : user

**Comment by MM2-0** [comment]
Should be [fixed in upstream library](https://android-review.googlesource.com/c/platform/frameworks/support/+/2425401), please reopen if issue still occurs in v1.23.0.
