### ISSUE TITLE
Crash when clicking on Accounts in settings (Services in french)

### ISSUE THREAD

**Issue by lbnt** [MM2-0/Kvaesitso#216]
Hi, when i click on Services (Accounts in English?) in the settings screen, Kvaesitso crash.
Here is the dump:
```
com.microsoft.identity.client.exception.MsalClientException: More than one app is listening for the URL scheme defined for BrowserTabActivity in the AndroidManifest. The package name of this other app is: org.tasks
	at com.microsoft.identity.client.PublicClientApplicationConfiguration.validateCustomTabRedirectActivity(PublicClientApplicationConfiguration.java:156)
	at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:34)
	at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:57)
	at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:27)
	at com.microsoft.identity.client.SingleAccountPublicClientApplication.<init>(SingleAccountPublicClientApplication.java:1)
	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:5)
	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:1)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:9)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:1)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:39)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e46ef75, Dispatchers.Main.immediate]
```
I confirm I have the Tasks app installed (org.tasks).

Thanks for you hard work on this project. It is really great!

**Comment by MM2-0** [comment]
This is actually a configuration error on Task's end. Sure I could catch the exception but Microsoft auth will not work until they fix their app.

I have created a bug report: https://github.com/tasks/tasks/issues/2073
