### ISSUE TITLE
Crashes after installing and adding favorites widget

### ISSUE THREAD

**Issue by iamgitcat** [MM2-0/Kvaesitso#286]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: fromIndex(6) > toIndex(0)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1018)
	at java.util.ArrayList.subList(ArrayList.java:1008)
	at de.mm20.launcher2.ui.launcher.widgets.favorites.FavoritesWidgetVM$favorites$1.invokeSuspend(FavoritesWidgetVM.kt:22)
	at de.mm20.launcher2.ui.launcher.widgets.favorites.FavoritesWidgetVM$favorites$1.invoke(FavoritesWidgetVM.kt:24)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:49)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:272)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:241)
[7 lines truncated]
```

## Device info
APP.VERSION : 1.23.0<br>APP.VERSIONCODE : 2023031400<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : fr.neamar.kiss<br>TIMEZONE : Europe/Moscow<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : 230216V1872<br>VERSION.SDK.NUMBER : 31<br>BOARD : TECNO-LF7n<br>BOOTLOADER : unknown<br>BRAND : TECNO<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : LF7n-H6918F-S-RU-230216V1872<br>FINGERPRINT : TECNO/LF7n-RU/TECNO-LF7n:12/SP1A.210812.016/230216V1872:user/release-keys<br>HARDWARE : mt6769<br>HOST : buildsrv-n134<br>ID : SP1A.210812.016<br>MANUFACTURER : TECNO<br>MODEL : TECNO LF7n<br>PRODUCT : LF7n-RU<br>TAGS : release-keys<br>TIME : 1676561448000<br>TYPE : user

**Comment by MM2-0** [comment]
Fixed in 1.23.1
