### ISSUE TITLE
Crash on create Favorite

### ISSUE THREAD

**Issue by Tealk** [MM2-0/Kvaesitso#287]
I get this error and cant start the Kvaesitso any more.

```
java.lang.IllegalArgumentException: fromIndex(5) > toIndex(4)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1018)
	at java.util.ArrayList.subList(ArrayList.java:1008)
	at de.mm20.launcher2.ui.launcher.widgets.favorites.FavoritesWidgetVM$favorites$1.invokeSuspend(FavoritesWidgetVM.kt:22)
	at de.mm20.launcher2.ui.launcher.widgets.favorites.FavoritesWidgetVM$favorites$1.invoke(FavoritesWidgetVM.kt:24)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invokeSuspend(Zip.kt:49)
	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$1$1.invoke(Zip.kt:20)
	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:272)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@7048aa2, androidx.compose.runtime.BroadcastFrameClock@a789333, StandaloneCoroutine{Cancelling}@ea266f0, AndroidUiDispatcher@4232469]
```

**Comment by MM2-0** [comment]
Fixed in 1.23.1
