### ISSUE TITLE
PackageManager$NameNotFoundException: ComponentInfo{[…]}

### ISSUE THREAD

**Issue by Vilianexe** [MM2-0/Kvaesitso#297]
## Description

i instaled a custom version of revanced, so it can be crashing, but apparently the home are also crashing too?(it wasn't hapeening in the old version of revanced)

## Strack trace

```
android.content.pm.PackageManager$NameNotFoundException: ComponentInfo{app.revanced.android.youtube/com.google.android.apps.youtube.app.application.Shell$ResultsActivity}
	at android.app.ApplicationPackageManager.getActivityInfo(ApplicationPackageManager.java:597)
	at android.app.ApplicationPackageManager.getActivityIcon(ApplicationPackageManager.java:1787)
	at de.mm20.launcher2.ui.component.SearchActionIconKt$SearchActionIcon$1$1.invokeSuspend(SearchActionIcon.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@52f51f4, androidx.compose.runtime.BroadcastFrameClock@6d66d1d, StandaloneCoroutine{Cancelling}@ff97b92, AndroidUiDispatcher@5cc4963]

```

## Device info
APP.VERSION : 1.23.1<br>APP.VERSIONCODE : 2023031500<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : America/Sao_Paulo<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : F415FUBS2CWB1<br>VERSION.SDK.NUMBER : 31<br>BOARD : exynos9611<br>BOOTLOADER : F415FUBS2CWB1<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : SP1A.210812.016.F415FUBS2CWB1<br>FINGERPRINT : samsung/f41ub/f41:12/SP1A.210812.016/F415FUBS2CWB1:user/release-keys<br>HARDWARE : exynos9611<br>HOST : 21DKGB10<br>ID : SP1A.210812.016<br>MANUFACTURER : samsung<br>MODEL : SM-F415F<br>PRODUCT : f41ub<br>TAGS : release-keys<br>TIME : 1676573949000<br>TYPE : user

**Comment by Vilianexe** [comment]
well, the crash seen to hapen only when teying to search, this look to make sense based in the notification 
![Screenshot_20230318-173737_Kvaesitso](https://user-images.githubusercontent.com/72302817/226137800-1a80ced4-4aa6-4852-81cb-de53ff8b9bab.png)

**Comment by gaykitty** [comment]
I having a similar crash. After I installed the Audible app from the Aurora Store, Kvaesitso started crash looping. Uninstalling Audable seems to have made it stop crashing. Here's the stack trace.

```
FATAL EXCEPTION: main
Process: de.mm20.launcher2.release, PID: 13657
android.content.pm.PackageManager$NameNotFoundException: com.audible.application
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:504)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:487)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:481)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:2047)
	at de.mm20.launcher2.ui.launcher.widgets.music.MusicWidgetKt.CustomActionIcon(MusicWidget.kt:50)
	at de.mm20.launcher2.ui.launcher.widgets.music.MusicWidgetKt$CustomActions$2$2.invoke(MusicWidget.kt:39)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:8)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:32)
	at androidx.compose.material3.IconButtonKt.IconButton(IconButton.kt:489)
	at de.mm20.launcher2.ui.launcher.widgets.music.MusicWidgetKt$CustomActions$2.invoke(MusicWidget.kt:56)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:22)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
	at androidx.compose.material3.TooltipKt.TooltipBox-XDn_Kpo(Tooltip.kt:513)
	at androidx.compose.material3.TooltipKt.PlainTooltipBox-nBX6wN0(Tooltip.kt:507)
	at de.mm20.launcher2.ui.launcher.widgets.music.MusicWidgetKt.CustomActions(MusicWidget.kt:107)
	at de.mm20.launcher2.ui.launcher.widgets.music.MusicWidgetKt.MusicWidget(MusicWidget.kt:2610)
	at de.mm20.launcher2.ui.launcher.widgets.music.MusicWidgetKt$MusicWidget$2.invoke(MusicWidget.kt:16)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:291)
	at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:144)
	at androidx.core.R$id.observeDerivedStateRecalculations(Unknown Source:44)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:124)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:36)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:18)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:75)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:350)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:9)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@8f28290, androidx.compose.ui.platform.MotionDurationScaleImpl@e69a789, StandaloneCoroutine{Cancelling}@fe438e, AndroidUiDispatcher@2ac37af]
```
