### ISSUE TITLE
MsalClientException: More than one app is listening for the URL scheme defined for BrowserTabActivity in the AndroidManifest. The package name of this other app is: […]

### ISSUE THREAD

**Issue by AshishChawla06** [MM2-0/Kvaesitso#320]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
com.microsoft.identity.client.exception.MsalClientException: More than one app is listening for the URL scheme defined for BrowserTabActivity in the AndroidManifest. The package name of this other app is: com.workjam.workjam
	at com.microsoft.identity.client.PublicClientApplicationConfiguration.validateCustomTabRedirectActivity(PublicClientApplicationConfiguration.java:156)
	at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:34)
	at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:57)
	at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:27)
	at com.microsoft.identity.client.SingleAccountPublicClientApplication.<init>(SingleAccountPublicClientApplication.java:1)
	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:5)
	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:1)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:9)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher.access$1000(CommandDispatcher.java:1)
	at com.microsoft.identity.common.java.controllers.CommandDispatcher$4.run(CommandDispatcher.java:39)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
[6 lines truncated]
```

## Device info
APP.VERSION : 1.23.1<br>APP.VERSIONCODE : 2023031500<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : America/Edmonton<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 9680964<br>VERSION.SDK.NUMBER : 33<br>BOARD : raven<br>BOOTLOADER : slider-1.2-9465321<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : TQ2A.230305.008.F1<br>FINGERPRINT : google/raven/raven:13/TQ2A.230305.008.F1/9680964:user/release-keys<br>HARDWARE : raven<br>HOST : abfarm-release-rbe-64-2004-0063<br>ID : TQ2A.230305.008.F1<br>MANUFACTURER : Google<br>MODEL : Pixel 6 Pro<br>PRODUCT : raven<br>TAGS : release-keys<br>TIME : 1677781917000<br>TYPE : user

**Comment by exstntlmsnthrp** [comment]
That seems to be caused by workjam, not Kvaesitso.

**Comment by AshishChawla06** [comment]
Oh thanks

**Comment by MM2-0** [comment]
Yes, it's a misconfiguration on Workjams side, but I guess I should handle this case better, make only the Microsoft integration fail to load instead of the whole launcher.
