### ISSUE TITLE
Newbie reporting a bug 

### ISSUE THREAD

**Issue by Knaive768** [MM2-0/Kvaesitso#331]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=225032567, result=0, data=Intent { (has extras) }} to activity {de.mm20.launcher2.release/de.mm20.launcher2.ui.launcher.LauncherActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: X.1ni
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5423)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5462)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2260)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1037)
[27 lines truncated]
```

## Device info
APP.VERSION : 1.23.1<br>APP.VERSIONCODE : 2023031500<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : V13.0.10.0.SKFINXM<br>VERSION.SDK.NUMBER : 31<br>BOARD : sweetin<br>BOOTLOADER : unknown<br>BRAND : Redmi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : SKQ1.210908.001 test-keys<br>FINGERPRINT : Redmi/sweetin/sweetin:12/SKQ1.210908.001/V13.0.10.0.SKFINXM:user/release-keys<br>HARDWARE : qcom<br>HOST : non-pangu-pod-1jblp<br>ID : SKQ1.210908.001<br>MANUFACTURER : Xiaomi<br>MODEL : M2101K6P<br>PRODUCT : sweetin<br>TAGS : release-keys<br>TIME : 1676861921000<br>TYPE : user

**Comment by Knaive768** [comment]
Search error on mi note 10 pro android 12
