### ISSUE TITLE
Unknown error logs in 1.24.1

### ISSUE THREAD

**Issue by exstntlmsnthrp** [MM2-0/Kvaesitso#353]
I'm getting many of the following errors in the crash reporter. I've never seen them show up before. Nearly 50 between the two types, just from today. 

Any ideas? Is this from the weather widget? Something else?

```
java.net.UnknownHostException: Unable to resolve host "weather.ls.hereapi.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:6)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:407)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:150)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:153)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:97)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
```

The other one that is also coming up. 

```
java.net.UnknownHostException: Unable to resolve host "www.ecb.europa.eu": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:6)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:407)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:150)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:153)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:97)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:42)
	at de.mm20.launcher2.currencies.ExchangeRateWorker.doWork(ExchangeRateWorker.kt:41)
	at androidx.work.Worker$1.run(Worker.java:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 19 more
```

Phone: Pixel 7 Pro
Android: 13
Kvaesitso: 1.24.1
App source: GitHub

**Comment by MM2-0** [comment]
Possibly your device was offline when the launcher attempted to fetch new data. Nothing to worry about.

**Comment by exstntlmsnthrp** [comment]
Thanks for commenting.
