### ISSUE TITLE
IllegalArgumentException: Unknown package: com.Alwaystastic.RocketIO

### ISSUE THREAD

**Issue by pravusuman2003** [MM2-0/Kvaesitso#359]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: Unknown package: com.Alwaystastic.RocketIO
	at android.os.Parcel.createException(Parcel.java:2078)
	at android.os.Parcel.readException(Parcel.java:2042)
	at android.os.Parcel.readException(Parcel.java:1990)
	at android.content.pm.IPackageManager$Stub$Proxy.getInstallerPackageName(IPackageManager.java:6695)
	at android.app.ApplicationPackageManager.getInstallerPackageName(ApplicationPackageManager.java:2084)
	at de.mm20.launcher2.compat.PackageManagerCompat.getInstallSource(PackageManagerCompat.kt:39)
	at de.mm20.launcher2.ui.launcher.search.apps.AppItemKt.AppItem(AppItem.kt:1232)
	at de.mm20.launcher2.ui.launcher.search.apps.AppItemKt$AppItemGridPopup$2.invoke(AppItem.kt:115)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:32)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:12)
	at androidx.compose.animation.AnimatedContentKt$AnimatedContent$5$1$4.invoke(AnimatedContent.kt:94)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:22)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:11)
	at androidx.compose.animation.AnimatedVisibilityKt.AnimatedEnterExitImpl(AnimatedVisibility.kt:1922)
[49 lines truncated]
```

## Device info
APP.VERSION : 1.24.1<br>APP.VERSIONCODE : 2023041800<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : 7511028<br>VERSION.SDK.NUMBER : 29<br>BOARD : QC_Reference_Phone<br>BOOTLOADER : unknown<br>BRAND : google<br>CPU_ABI : armeabi-v7a<br>CPU_ABI2 : armeabi<br>DISPLAY : RQ3A.210905.001<br>FINGERPRINT : google/sailfish/sailfish:10/QP1A.191005.007.A3/5972272:user/release-keys<br>HARDWARE : qcom<br>HOST : abfarm813<br>ID : RQ3A.210905.001<br>MANUFACTURER : Google<br>MODEL : Pixel<br>PRODUCT : sailfish<br>TAGS : release-keys<br>TIME : 1625099061000<br>TYPE : user

**Comment by exstntlmsnthrp** [comment]
This crash looks related to gravity.io (com.alwaystastic.rocketio) and not related to Kvaesitso.

**Comment by pravusuman2003** [comment]
Thank you for your response. And I want to give one suggestion, make the
app drawer a little smoother while scrolling. The scrolling lags on low end
devices like on 2GB ram phone.
