### ISSUE TITLE
Crashes upon going to settings after adding a widget

### ISSUE THREAD

**Issue by yant0** [MM2-0/Kvaesitso#372]
## Description

Launcher crashed everytime i open settings, i was trying to add a widget, it worked but now the setting panels crashes. I tried removing the widget and deleting app data but the crash persisted.

## Strack trace

```
java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.stopListening(IAppWidgetService.java:789)
	at android.appwidget.AppWidgetHost.stopListening(AppWidgetHost.java:257)
	at de.mm20.launcher2.ui.launcher.widgets.WidgetColumnKt$WidgetColumn$1$1.invokeSuspend(WidgetColumn.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
[13 lines truncated]
```

## Device info
APP.VERSION : 1.24.2<br>APP.VERSIONCODE : 2023042300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Jakarta<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : eng.kvije6.20220928.173228<br>VERSION.SDK.NUMBER : 30<br>BOARD : sdm636<br>BOOTLOADER : unknown<br>BRAND : asus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : RQ3A.211001.001<br>FINGERPRINT : google/raven/raven:13/TP1A.220905.004/8927612:user/release-keys<br>HARDWARE : qcom<br>HOST : harshainstance-1<br>ID : RQ3A.211001.001<br>MANUFACTURER : asus<br>MODEL : Zenfone Max Pro M1<br>PRODUCT : WW_X00T<br>TAGS : release-keys<br>TIME : 1664386346000<br>TYPE : user

**Comment by exstntlmsnthrp** [comment]
I believe this may be a duplicate and/or related to #371.
