### ISSUE TITLE
App crash when trying to complete conversation

### ISSUE THREAD

**Issue by exstntlmsnthrp** [MM2-0/Kvaesitso#390]
Kvaesitso crashed whilst I was experimenting with various conversions from the search bar. Interestingly, most of the attempted conversions did not work. The only thing that worked was distance/length. 

Crash report

```
java.lang.IllegalStateException: Offset is unspecified
at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:29)
at androidx.compose.ui.node.NodeCoordinator.fromParentPosition-MK-Hz9U(NodeCoordinator.kt:3)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:19)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
at androidx.compose.ui.node.NodeCoordinator.localPositionOf-R5De75A(NodeCoordinator.kt:77)
at androidx.compose.ui.node.NodeCoordinator.windowToLocal-MK-Hz9U(NodeCoordinator.kt:29)
at androidx.compose.foundation.text.selection.TextFieldSelectionManagerKt.isSelectionHandleInVisibleBound(TextFieldSelectionManager.kt:27)
at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$onPositionedModifier$1.invoke(CoreTextField.kt:92)
at androidx.compose.ui.layout.OnGloballyPositionedNode.onGloballyPositioned(OnGloballyPositionedModifier.kt:3)
at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:53)
at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks(MeasureAndLayoutDelegate.kt:68)
at androidx.compose.ui.platform.AndroidComposeView.updatePositionCacheAndDispatch(AndroidComposeView.android.kt:58)
at androidx.compose.ui.platform.AndroidComposeView$$ExternalSyntheticLambda0.onGlobalLayout(R8$$SyntheticClass:10)
at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1148)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3492)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2350)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9194)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
at android.view.Choreographer.doCallbacks(Choreographer.java:899)
at android.view.Choreographer.doFrame(Choreographer.java:832)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7884)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
Logs

```
Device: cheetah
SDK version: 33
====================================
05-06 20:36:15.203  3524  3524 E MM20    : kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@3285447
05-06 20:36:37.691  3524  3524 D InsetsController: show(ime(), fromIme=false)
05-06 20:36:37.691  3524  3524 D InputMethodManager: showSoftInput() view=androidx.compose.ui.platform.AndroidComposeView{e4f9caa VFED..... .F....ID 0,0-1440,3120 aid=1073741828} flags=0 reason=SHOW_SOFT_INPUT_BY_INSETS_API
05-06 20:36:37.744  3524  3524 W RecordingIC: requestCursorUpdates is not supported
05-06 20:36:37.871  3524  3524 D InsetsController: show(ime(), fromIme=true)
05-06 20:36:55.495  3524  3524 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:36:55.495  3524  3524 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-06 20:36:55.824  3524  3745 D OpenGLRenderer: endAllActiveAnimators on 0xb400007495197070 (UnprojectedRipple) with handle 0xb4000073a523d8a0
05-06 20:37:08.145  3524  3524 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:37:08.145  3524  3524 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-06 20:37:08.171  3524  3524 D AndroidRuntime: Shutting down VM
--------- beginning of crash
05-06 20:37:08.173  3524  3524 E AndroidRuntime: FATAL EXCEPTION: main
05-06 20:37:08.173  3524  3524 E AndroidRuntime: Process: de.mm20.launcher2.release, PID: 3524
05-06 20:37:08.173  3524  3524 E AndroidRuntime: java.lang.IllegalStateException: Offset is unspecified
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:29)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.fromParentPosition-MK-Hz9U(NodeCoordinator.kt:3)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:19)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.ancestorToLocal-R5De75A(NodeCoordinator.kt:15)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.localPositionOf-R5De75A(NodeCoordinator.kt:77)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.NodeCoordinator.windowToLocal-MK-Hz9U(NodeCoordinator.kt:29)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.foundation.text.selection.TextFieldSelectionManagerKt.isSelectionHandleInVisibleBound(TextFieldSelectionManager.kt:27)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.foundation.text.CoreTextFieldKt$CoreTextField$onPositionedModifier$1.invoke(CoreTextField.kt:92)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.layout.OnGloballyPositionedNode.onGloballyPositioned(OnGloballyPositionedModifier.kt:3)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:53)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:81)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.dispatchOnPositionedCallbacks(MeasureAndLayoutDelegate.kt:68)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.updatePositionCacheAndDispatch(AndroidComposeView.android.kt:58)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView$$ExternalSyntheticLambda0.onGlobalLayout(R8$$SyntheticClass:10)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1148)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3492)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2350)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9194)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:832)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-06 20:37:08.173  3524  3524 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
05-06 20:37:08.177  3524  3524 D CrashUtil: crash report saved in : /storage/emulated/0/Android/data/de.mm20.launcher2.release/files/crashReports
05-06 20:37:08.189  3524  3524 I Process : Sending signal. PID: 3524 SIG: 9
05-06 20:37:08.291 32240 32240 I uncher2.release: Using CollectorTypeCC GC.
05-06 20:37:08.294 32240 32240 E uncher2.release: Not starting debugger since process cannot load the jdwp agent.
05-06 20:37:08.300 32240 32240 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10289; state: ENABLED
05-06 20:37:08.342 32240 32240 D nativeloader: Configuring classloader-namespace for other apk /data/app/~~cMRSkCKYE21W0hROMQTu1A==/de.mm20.launcher2.release-dWYvoxdYQQbpWofiOfoZFg==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~cMRSkCKYE21W0hROMQTu1A==/de.mm20.launcher2.release-dWYvoxdYQQbpWofiOfoZFg==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/de.mm20.launcher2.release
05-06 20:37:08.350 32240 32240 V GraphicsEnvironment: ANGLE Developer option for 'de.mm20.launcher2.release' set to: 'default'
05-06 20:37:08.351 32240 32240 V GraphicsEnvironment: ANGLE GameManagerService for de.mm20.launcher2.release: false
05-06 20:37:08.351 32240 32240 V GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
05-06 20:37:08.353 32240 32240 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-06 20:37:08.354 32240 32240 D NetworkSecurityConfig: No Network Security Config specified, using platform default
05-06 20:37:08.355 32240 32240 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
05-06 20:37:08.370 32240 32257 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10289; state: ENABLED
05-06 20:37:08.371 32240 32240 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
05-06 20:37:08.388 32240 32240 D CompatibilityChangeReporter: Compat change id reported: 183155436; UID 10289; state: ENABLED
05-06 20:37:08.443 32240 32240 I incfs   : Initial API level of the device: 33
05-06 20:37:08.443 32240 32240 W libc    : Access denied finding property "ro.incremental.enable"
05-06 20:37:08.443 32240 32240 I incfs   : ro.incremental.enable: on
05-06 20:37:08.441 32240 32240 W uncher2.release: type=1400 audit(0.0:6207): avc: denied { read } for name="u:object_r:incremental_prop:s0" dev="tmpfs" ino=224 scontext=u:r:untrusted_app:s0:c33,c257,c512,c768 tcontext=u:object_r:incremental_prop:s0 tclass=file permissive=0 app=de.mm20.launcher2.release
05-06 20:37:08.441 32240 32240 W uncher2.release: type=1400 audit(0.0:6208): avc: denied { read } for name="filesystems" dev="proc" ino=4026532062 scontext=u:r:untrusted_app:s0:c33,c257,c512,c768 tcontext=u:object_r:proc_filesystems:s0 tclass=file permissive=0 app=de.mm20.launcher2.release
05-06 20:37:08.443 32240 32240 I incfs   : IncFs_Features: v2
05-06 20:37:08.444 32240 32240 I incfs-mounts: [incfs] Loaded incremental-fs mount info: 1 instances, 2 mount points
05-06 20:37:08.576 32240 32240 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:37:08.576 32240 32240 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-06 20:37:08.590 32240 32240 D MM20    : Notification listener connected
05-06 20:37:08.610 32240 32240 D CompatibilityChangeReporter: Compat change id reported: 170233598; UID 10289; state: DISABLED
05-06 20:37:08.683 32240 32290 D MM20    : Icon pack com.donnnno.arcticons is up to date
05-06 20:37:13.738 32240 32303 D ProfileInstaller: Skipping profile installation for de.mm20.launcher2.release
05-06 20:37:15.195 32240 32240 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:37:15.195 32240 32240 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-06 20:37:15.204 32240 32240 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10289; state: ENABLED
05-06 20:37:19.728 32240 32248 I uncher2.release: Background concurrent copying GC freed 359455(12MB) AllocSpace objects, 12(252KB) LOS objects, 75% free, 8537KB/33MB, paused 134us,27us total 145.576ms
05-06 20:37:35.780 32240 32258 D OpenGLRenderer: endAllActiveAnimators on 0xb400007495207480 (UnprojectedRipple) with handle 0xb4000073a51dd690
05-06 20:37:41.547 32240 32240 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:37:41.547 32240 32240 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-06 20:37:43.164 32240 32255 E DatabaseUtils: Writing exception to parcel
05-06 20:37:43.164 32240 32255 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading de.mm20.launcher2.content.GenericFileProvider uri content://de.mm20.launcher2.release.fileprovider/external_files/Android/data/de.mm20.launcher2.release/files/crashReports/2023-05-06%2020%3A37%3A08_crash.txt from pid=32417, uid=1000 requires the provider be exported, or grantUriPermission()
05-06 20:37:43.164 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:879)
05-06 20:37:43.164 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:707)
05-06 20:37:43.164 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:246)
05-06 20:37:43.164 32240 32255 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
05-06 20:37:43.164 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
05-06 20:37:43.164 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
05-06 20:37:43.178 32240 32255 E DatabaseUtils: Writing exception to parcel
05-06 20:37:43.178 32240 32255 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading de.mm20.launcher2.content.GenericFileProvider uri content://de.mm20.launcher2.release.fileprovider/external_files/Android/data/de.mm20.launcher2.release/files/crashReports/2023-05-06%2020%3A37%3A08_crash.txt from pid=32417, uid=1000 requires the provider be exported, or grantUriPermission()
05-06 20:37:43.178 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:879)
05-06 20:37:43.178 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:707)
05-06 20:37:43.178 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:246)
05-06 20:37:43.178 32240 32255 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
05-06 20:37:43.178 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
05-06 20:37:43.178 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
05-06 20:37:43.214 32240 32255 E DatabaseUtils: Writing exception to parcel
05-06 20:37:43.214 32240 32255 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading de.mm20.launcher2.content.GenericFileProvider uri content://de.mm20.launcher2.release.fileprovider/external_files/Android/data/de.mm20.launcher2.release/files/crashReports/2023-05-06%2020%3A37%3A08_crash.txt from pid=32417, uid=1000 requires the provider be exported, or grantUriPermission()
05-06 20:37:43.214 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:879)
05-06 20:37:43.214 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:707)
05-06 20:37:43.214 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:246)
05-06 20:37:43.214 32240 32255 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
05-06 20:37:43.214 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
05-06 20:37:43.214 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
05-06 20:37:57.949 32240 32240 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:37:57.949 32240 32240 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-06 20:38:37.865 32240 32240 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:38:37.865 32240 32240 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-06 20:39:04.240 32240 32240 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:39:04.240 32240 32240 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-06 20:40:44.638 32240 32240 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:40:44.638 32240 32240 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
05-06 20:41:03.495 32240 32255 E DatabaseUtils: Writing exception to parcel
05-06 20:41:03.495 32240 32255 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading de.mm20.launcher2.content.GenericFileProvider uri content://de.mm20.launcher2.release.fileprovider/external_files/Android/data/de.mm20.launcher2.release/files/crashReports/2023-05-06%2020%3A37%3A08_crash.txt from pid=32417, uid=1000 requires the provider be exported, or grantUriPermission()
05-06 20:41:03.495 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:879)
05-06 20:41:03.495 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:707)
05-06 20:41:03.495 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:246)
05-06 20:41:03.495 32240 32255 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
05-06 20:41:03.495 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
05-06 20:41:03.495 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
05-06 20:41:03.504 32240 32255 E DatabaseUtils: Writing exception to parcel
05-06 20:41:03.504 32240 32255 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading de.mm20.launcher2.content.GenericFileProvider uri content://de.mm20.launcher2.release.fileprovider/external_files/Android/data/de.mm20.launcher2.release/files/crashReports/2023-05-06%2020%3A37%3A08_crash.txt from pid=32417, uid=1000 requires the provider be exported, or grantUriPermission()
05-06 20:41:03.504 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:879)
05-06 20:41:03.504 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:707)
05-06 20:41:03.504 32240 32255 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:246)
05-06 20:41:03.504 32240 32255 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
05-06 20:41:03.504 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
05-06 20:41:03.504 32240 32255 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
05-06 20:41:03.521 32240 32253 E DatabaseUtils: Writing exception to parcel
05-06 20:41:03.521 32240 32253 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading de.mm20.launcher2.content.GenericFileProvider uri content://de.mm20.launcher2.release.fileprovider/external_files/Android/data/de.mm20.launcher2.release/files/crashReports/2023-05-06%2020%3A37%3A08_crash.txt from pid=32417, uid=1000 requires the provider be exported, or grantUriPermission()
05-06 20:41:03.521 32240 32253 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:879)
05-06 20:41:03.521 32240 32253 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:707)
05-06 20:41:03.521 32240 32253 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:246)
05-06 20:41:03.521 32240 32253 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:107)
05-06 20:41:03.521 32240 32253 E DatabaseUtils: 	at android.os.Binder.execTransactInternal(Binder.java:1280)
05-06 20:41:03.521 32240 32253 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:1244)
05-06 20:41:27.662 32240 32240 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
05-06 20:41:27.662 32240 32240 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
null
```

**Comment by MM2-0** [comment]
Haven't seen this in a long time, so I assume it's fixed (?)
