### ISSUE TITLE
PendingIntent$CanceledException

### ISSUE THREAD

**Issue by tanmaytez** [MM2-0/Kvaesitso#393]
```
android.app.PendingIntent$CanceledException
	at android.app.PendingIntent.send(PendingIntent.java:962)
	at android.app.PendingIntent.send(PendingIntent.java:774)
	at de.mm20.launcher2.ui.launcher.widgets.music.MusicWidgetKt$MusicWidget$1$2$3.invoke(MusicWidget.kt:16)
	at androidx.compose.foundation.CombinedClickablePointerInputNode$pointerInput$5.invoke(Clickable.kt:13)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1.invokeSuspend(TapGestureDetector.kt:333)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:78)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:129)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:44)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:17)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:51)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:31)
	at androidx.compose.foundation.AbstractClickablePointerInputNode.onPointerEvent-H0pRuoY(Clickable.kt:3)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:91)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:73)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:73)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:73)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:73)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:73)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:73)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:73)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:73)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:49)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:158)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:78)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:228)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:90)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:573)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1911)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4272)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:3)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
	at android.view.View.dispatchPointerEvent(View.java:14899)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6682)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6453)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5922)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5984)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6119)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5953)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6176)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5926)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5984)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5945)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5953)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5926)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8942)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8893)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8854)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9085)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:260)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:339)
	at android.os.Looper.loopOnce(Looper.java:179)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8191)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

APP.VERSION : 1.24.2
APP.VERSIONCODE : 2023042300
APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=
LAUNCHER.APP : de.mm20.launcher2.release
TIMEZONE : Asia/Kolkata
VERSION.RELEASE : 12
VERSION.INCREMENTAL : Q.e3b1e0_c-490d
VERSION.SDK.NUMBER : 31
BOARD : kona
BOOTLOADER : unknown
BRAND : realme
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : RMX2076_11_F.12
FINGERPRINT : realme/RMX2076/RMX2076L1:12/RKQ1.211103.002/Q.e3b1e0_c-490d:user/release-keys
HARDWARE : qcom
HOST : dg02-pool03-kvm236
ID : RKQ1.211103.002
MANUFACTURER : realme
MODEL : RMX2076
PRODUCT : RMX2076
TAGS : release-keys
TIME : 1676280464000
TYPE : user

**Comment by MM2-0** [comment]
Not a crash, no further action required.
