### ISSUE TITLE
Fail

### ISSUE THREAD

**Issue by EmiJaeger** [MM2-0/Kvaesitso#414]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.SecurityException: Permission Denial: opening provider com.android.calendar.hap.HolidayRecessContentProvider from ProcessRecord{a78c5b9 23830:de.mm20.launcher2.release/u0a1102} (pid=23830, uid=11102) requires com.android.calendar.huawei.permission.CALENDAR_RECESS or com.huawei.calendar.permission.WRITE_CALENDAR_RECESS
	at android.os.Parcel.createException(Parcel.java:2090)
	at android.os.Parcel.readException(Parcel.java:2058)
	at android.os.Parcel.readException(Parcel.java:2006)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5268)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7742)
	at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2962)
	at android.content.ContentResolver.acquireProvider(ContentResolver.java:2158)
	at android.content.ContentResolver.call(ContentResolver.java:2094)
	at android.content.ContentResolver.call(ContentResolver.java:2079)
	at com.android.calendar.mycalendar.Utils.getWidgetRecessAndLocalData(Utils.java:554)
	at com.android.calendar.mycalendar.CalendarSwitchView$QueryHandler$WorkThreadHandler.handleMessage(CalendarSwitchView.java:2070)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.os.HandlerThread.run(HandlerThread.java:67)
[9 lines truncated]
```

## Device info
APP.VERSION : 1.25.1<br>APP.VERSIONCODE : 2023052200<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : com.huawei.android.launcher<br>TIMEZONE : America/Mexico_City<br>VERSION.RELEASE : 10<br>VERSION.INCREMENTAL : 10.1.0.294C69<br>VERSION.SDK.NUMBER : 29<br>BOARD : LYA<br>BOOTLOADER : unknown<br>BRAND : HUAWEI<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : LYA-L09 10.1.0.294(C69E11R1P5)<br>FINGERPRINT : HUAWEI/LYA-L09/HWLYA:10/HUAWEILYA-L09/10.1.0.294C69:user/release-keys<br>HARDWARE : kirin980<br>HOST : cn-central-1b-2c4d5e0081596272452198-3424159072-thxw3<br>ID : HUAWEILYA-L09<br>MANUFACTURER : HUAWEI<br>MODEL : LYA-L09<br>PRODUCT : LYA-L09<br>TAGS : release-keys<br>TIME : 1596276019000<br>TYPE : user

**Comment by exstntlmsnthrp** [comment]
The crash is caused by your calendar app, not by Kvaesitso.

**Comment by MM2-0** [comment]
I don't know what causes this but `com.android.calendar.huawei.permission.CALENDAR_RECESS` is not a standard Android permission so apps shouldn't need it to function properly.
