### ISSUE TITLE
Randomly Crashes

### ISSUE THREAD

**Issue by CreepKing8288** [MM2-0/Kvaesitso#455]
If I open some apps kvaesitso stop responding

Help?

**Comment by pulkit-999** [comment]
If possible tell the specific apps you are talking about?

**Comment by CreepKing8288** [comment]
system apps like settings, Clock, ect..

**Comment by exstntlmsnthrp** [comment]
Can you share the kvaesitso logs, please?

**Comment by CreepKing8288** [comment]
java.net.UnknownHostException: Unable to resolve host "api.openweathermap.org": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
	at java.net.InetAddress.getAllByName(InetAddress.java:1154)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:6)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:407)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:150)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:153)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:144)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:97)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
	... 17 more

**Comment by CreepKing8288** [comment]
/

**Comment by CreepKing8288** [comment]
[Full day crash report](https://drive.google.com/drive/folders/1ijDiNxW43VOiLL4T075HQ0v0HwfyaPCV)
