### ISSUE TITLE
App crash (diffrent to other issue as far as im concerened)

### ISSUE THREAD

**Issue by shruuub** [MM2-0/Kvaesitso#48]
Steps to reproduce (at least for me)
Have the protonmail app (beta) on your favorites bar and try to open it. (Opening it from app bar > no crash) 
Logs (Crash message):
`
java.lang.SecurityException: Permission Denial: starting Intent { flg=0x10000000 cmp=ch.protonmail.android/.activities.SplashActivity } from ProcessRecord{b97e1c9 1519:de.mm20.launcher2.release/u0a404} (pid=1519, uid=10404) not exported from uid 10284
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:4276)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
	at android.app.Activity.startActivityForResult(Activity.java:5377)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:647)
	at android.app.Activity.startActivity(Activity.java:5717)
	at de.mm20.launcher2.search.data.LauncherApp.launch(LauncherApp.kt:83)
	at de.mm20.launcher2.ui.launcher.search.common.SearchableItemVM.launch(SearchableItemVM.kt:66)
	at de.mm20.launcher2.ui.launcher.search.common.GridItemKt$GridItem$1$2.invoke(GridItem.kt:69)
	at de.mm20.launcher2.ui.launcher.search.common.GridItemKt$GridItem$1$2.invoke(GridItem.kt:60)
	at de.mm20.launcher2.ui.component.ShapedLauncherIconKt$ShapedLauncherIcon$1$2$1.invoke(ShapedLauncherIcon.kt:68)
	at de.mm20.launcher2.ui.component.ShapedLauncherIconKt$ShapedLauncherIcon$1$2$1.invoke(ShapedLauncherIcon.kt:67)
	at androidx.compose.foundation.ClickableKt$combinedClickable$4$gesture$1$4.invoke-k-4lQ0M(Clickable.kt:339)
	at androidx.compose.foundation.ClickableKt$combinedClickable$4$gesture$1$4.invoke(Clickable.kt:318)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1$1.invokeSuspend(TapGestureDetector.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:509)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:404)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:417)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:310)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:297)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:179)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:98)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:80)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1223)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1173)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1113)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3920)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3594)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:913)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1957)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4182)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:871)
	at android.view.View.dispatchPointerEvent(View.java:15458)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7457)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7233)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:10014)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1344)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1260)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:894)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1721)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1571)
`

**Comment by MM2-0** [comment]
I assume they changed their main activity so unpinning and re-pinning should fix it. Thanks for the report though, I should definetly catch this error and not crash the launcher.

**Comment by shruuub** [comment]
> I assume they changed their main activity so unpinning and re-pinning should fix it. Thanks for the report though, I should definetly catch this error and not crash the launcher.

Yup, unpinning and pinning does fix it, even though the icon has changed, but that's probably since it's the beta again :)
