### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Blackheart2062** [MM2-0/Kvaesitso#490]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.NullPointerException: Attempt to read from field 'com.android.server.appwidget.AppWidgetServiceImpl$ProviderId com.android.server.appwidget.AppWidgetServiceImpl$Provider.id' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2394)
	at android.os.Parcel.createException(Parcel.java:2372)
	at android.os.Parcel.readException(Parcel.java:2355)
	at android.os.Parcel.readException(Parcel.java:2297)
	at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.stopListening(IAppWidgetService.java:789)
	at android.appwidget.AppWidgetHost.stopListening(AppWidgetHost.java:263)
	at de.mm20.launcher2.ui.launcher.widgets.WidgetColumnKt$WidgetColumn$1$1.invokeSuspend(WidgetColumn.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
[6 lines truncated]
```

## Device info
APP.VERSION : 1.24.2<br>APP.VERSIONCODE : 2023042300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Dhaka<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : eng.compil.20230504.145730<br>VERSION.SDK.NUMBER : 30<br>BOARD : k65v1_64_bsp<br>BOOTLOADER : unknown<br>BRAND : vivo<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : RP1A.200720.012 release-keys<br>FINGERPRINT : vivo/2026EC/2026:11/RP1A.200720.012/compiler0504145542:user/release-keys<br>HARDWARE : mt6765<br>HOST : comsz01078161<br>ID : RP1A.200720.012<br>MANUFACTURER : vivo<br>MODEL : V2043<br>PRODUCT : 2026EC<br>TAGS : release-keys<br>TIME : 1683183342000<br>TYPE : user

**Comment by MM2-0** [comment]
You are using an outdated version of Kvaesitso. Please update to the [lastest version](github.com/MM2-0/Kvaesitso/releases/latest).
