### ISSUE TITLE
SQLiteDatabaseCorruptException: file is not a database

### ISSUE THREAD

**Issue by AdityaMH** [MM2-0/Kvaesitso#502]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
android.database.sqlite.SQLiteDatabaseCorruptException: file is not a database (code 26 SQLITE_NOTADB): , while compiling: PRAGMA journal_mode
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
	at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:729)
	at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:376)
	at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:306)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.tryAcquireNonPrimaryConnectionLocked(SQLiteConnectionPool.java:989)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:695)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:380)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:896)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
[16 lines truncated]
```

## Device info
APP.VERSION : 1.26.4<br>APP.VERSIONCODE : 2023071201<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>VERSION.RELEASE : 10<br>VERSION.INCREMENTAL : V12.0.6.0.QJQIDXM<br>VERSION.SDK.NUMBER : 29<br>BOARD : lime<br>BOOTLOADER : unknown<br>BRAND : Redmi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : Android-Q-build-20210624184126<br>FINGERPRINT : Redmi/lime_id/lime:10/QKQ1.200830.002/V12.0.6.0.QJQIDXM:user/release-keys<br>HARDWARE : qcom<br>HOST : c5-miui-ota-bd216.bj<br>ID : QKQ1.200830.002<br>MANUFACTURER : Xiaomi<br>MODEL : M2010J19SG<br>PRODUCT : lime_id<br>TAGS : release-keys<br>TIME : 1624535114000<br>TYPE : user

**Comment by MM2-0** [comment]
Corrupt database. Not sure what happened, but the only way around this is wiping the launcher settings. Don't think this is a regular thing, so I'm closing this for now. Please reopen if this happened more than once.
