### ISSUE TITLE
[BUG] "Favourite" apps crash launcher

### ISSUE THREAD

**Issue by doasu** [MM2-0/Kvaesitso#517]
What are the steps to reproduce this issue?
-------------------------------------------
1. Open Kvaesitso (Launcher)
+ Add an app to favourites  

or
+ Use Kvaesitso until an app is automatically added to favourites

What happens?
-------------
Kvaesitso crashes and refuses to launch unless application data is cleared (i.e. favourite apps are empty)

What were you expecting to happen?
----------------------------------
Apps would be added to favourites and the Launcher would continue to work.

Any logs, error output, etc?
----------------------------
Crash report:
```
type: crash
osVersion: google/panther/panther:13/TQ3A.230805.001/2023080800:user/release-keys
package: de.mm20.launcher2.release:2023071201
process: de.mm20.launcher2.release
processUptime: 1224 + 288 ms
installer: com.machiav3lli.fdroid

java.lang.SecurityException: Cannot resolve activity for unrelated profile 0
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.content.pm.ILauncherApps$Stub$Proxy.resolveLauncherActivityInternal(ILauncherApps.java:852)
	at android.content.pm.LauncherApps.resolveActivity(LauncherApps.java:791)
	at de.mm20.launcher2.search.data.LauncherAppDeserializer.deserialize(AppSerialization.kt:78)
	at de.mm20.launcher2.searchable.SearchableRepositoryImpl.fromDatabaseEntity(SearchableRepository.kt:209)
	at de.mm20.launcher2.searchable.SearchableRepositoryImpl$get$$inlined$map$1$2.emit(Emitters.kt:78)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:24)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:142)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@10e0588, Dispatchers.Main.immediate]
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.pm.UserManagerService$LocalService.isProfileAccessible(UserManagerService.java:6344)
	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.canAccessProfile(LauncherAppsService.java:409)
	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.canAccessProfile(LauncherAppsService.java:385)
	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.resolveLauncherActivityInternal(LauncherAppsService.java:599)
	at android.content.pm.ILauncherApps$Stub.onTransact(ILauncherApps.java:355)
```

Device info
------------------------
APP.VERSION : 1.26.4<br>APP.VERSIONCODE : 2023071201<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : app.lawnchair<br>TIMEZONE : x/y<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : 2023080800<br>VERSION.SDK.NUMBER : 33<br>BOARD : panther<br>BOOTLOADER : cloudripper-1.0-9894666<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : TQ3A.230805.001.2023080800<br>FINGERPRINT : google/panther/panther:13/TQ3A.230805.001/2023080800:user/release-keys<br>HARDWARE : panther<br>HOST : grapheneos<br>ID : TQ3A.230805.001<br>MANUFACTURER : Google<br>MODEL : Pixel 7<br>PRODUCT : panther<br>TAGS : release-keys<br>TIME : 1691529983000<br>TYPE : user

Any other comments?
-------------------
I am running Kvaesitso in a non-root user profile which - looking at the crash report - might have something to do with this behaviour.

What versions of software are you using?
----------------------------------------
**Operating System:** GrapheneOS/Android 13

**Kvaesitso Version:** 1.26.4 && 1.26.4-20230826-nightly && 1.21.1

**Comment by MM2-0** [comment]
Related: #301

**Comment by doasu** [comment]
> Related: #301

It's the same issue.
