### ISSUE TITLE
Crash while searching

### ISSUE THREAD

**Issue by davidoskky** [MM2-0/Kvaesitso#527]
## Description

Tap the search bar
Type "se"

It crashes consistently every time. 
If I type "s" it does not crash.
If I quickly type something longer, say "sen" it does not crash.
If I type "sen" and delete the n it does crash.

## Strack trace

```
java.lang.IllegalArgumentException: Can't represent a size of 1251966 in Constraints
	at androidx.compose.ui.unit.Constraints$Companion.bitsNeedForSize(Constraints.kt:41)
	at androidx.compose.ui.unit.Constraints$Companion.createConstraints-Zbe2FdA$ui_unit_release(Constraints.kt:18)
	at androidx.compose.ui.unit.ConstraintsKt.Constraints(Constraints.kt:27)
	at androidx.compose.ui.unit.ConstraintsKt.Constraints$default(Constraints.kt:15)
	at androidx.compose.foundation.text.modifiers.LayoutUtilsKt.finalConstraints-tfFHcEY(LayoutUtils.kt:54)
	at androidx.compose.foundation.text.modifiers.ParagraphLayoutCache.layoutText-K40F9xA(ParagraphLayoutCache.kt:13)
	at androidx.compose.foundation.text.modifiers.TextStringSimpleNode.measure-3p2s80s(TextStringSimpleNode.kt:199)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:15)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:6)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:15)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Padding.kt:38)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:15)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:9)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:64)
[132 lines truncated]
```

## Device info
APP.VERSION : 1.26.4-fdroid<br>APP.VERSIONCODE : 2023071201<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Madrid<br>VERSION.RELEASE : 10<br>VERSION.INCREMENTAL : V12.5.1.0.QFGEUXM<br>VERSION.SDK.NUMBER : 29<br>BOARD : sdm660<br>BOOTLOADER : unknown<br>BRAND : xiaomi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : QKQ1.190910.002 V12.5.1.0.QFGEUXM<br>FINGERPRINT : xiaomi/lavender_eea/lavender:10/QKQ1.190910.002/V12.5.1.0.QFGEUXM:user/release-keys<br>HARDWARE : qcom<br>HOST : c4-miui-ota-bd172.bj<br>ID : QKQ1.190910.002<br>MANUFACTURER : Xiaomi<br>MODEL : Redmi Note 7<br>PRODUCT : lavender_eea<br>TAGS : release-keys<br>TIME : 1630603680000<br>TYPE : user

**Comment by MM2-0** [comment]
Difficult to say what causes it, but probably it is some specific search result that crashes the launcher when it is loaded in. Can you try to disable the different search categories (calendar, contacts, files, …) one by one until it stop crashing? To narrow it down to the result causing this.

**Comment by davidoskky** [comment]
This seems to arise from the contacts search. I'm not sure which one is causing it: I have a large number of contacts which match that search.
