### ISSUE TITLE
Random crash when navigating to homescreen

### ISSUE THREAD

**Issue by gochuicod** [MM2-0/Kvaesitso#541]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: View=androidx.compose.ui.window.PopupLayout{ce08a5f V.E...... ......ID 0,0-1078,456 #1020002 android:id/content} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:733)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:591)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:155)
	at androidx.compose.ui.window.PopupLayoutHelperImpl.updateViewLayout(AndroidPopup.android.kt:17)
	at androidx.compose.ui.window.PopupLayout.updatePosition(AndroidPopup.android.kt:89)
	at androidx.compose.ui.window.PopupLayout.updateParentBounds$ui_release(AndroidPopup.android.kt:75)
	at androidx.compose.ui.window.PopupLayout.updateParentLayoutCoordinates(AndroidPopup.android.kt:4)
	at androidx.compose.ui.window.AndroidPopup_androidKt$Popup$7.invoke(AndroidPopup.android.kt:17)
	at androidx.compose.ui.layout.OnGloballyPositionedNode.onGloballyPositioned(OnGloballyPositionedModifier.kt:3)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:61)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:159)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:159)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:159)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:159)
[25 lines truncated]
```

## Device info
APP.VERSION : 1.26.4<br>APP.VERSIONCODE : 2023071201<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Asia/Manila<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : G990U2SQS6EWG9<br>VERSION.SDK.NUMBER : 33<br>BOARD : lahaina<br>BOOTLOADER : G990U2SQS6EWG9<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : TP1A.220624.014.G990U2SQS6EWG9<br>FINGERPRINT : samsung/r9q2sqw/r9q:13/TP1A.220624.014/G990U2SQS6EWG9:user/release-keys<br>HARDWARE : qcom<br>HOST : 21DJF822<br>ID : TP1A.220624.014<br>MANUFACTURER : samsung<br>MODEL : SM-G990U2<br>PRODUCT : r9q2sqw<br>TAGS : release-keys<br>TIME : 1690355244000<br>TYPE : user

*this doesn't really concern me much since it only occurs once in a blue moon but it would probably help the project*

**Comment by MM2-0** [comment]
Should be "fixed" by now since I'm not using popups anymore, but feel free to reopen if it happens again.
