### ISSUE TITLE
Crash when searching a word

### ISSUE THREAD

**Issue by kud** [MM2-0/Kvaesitso#544]
## Description

I think I was searching for a shortcut of a hidden app.

## Strack trace

```
java.lang.NullPointerException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:804)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2002)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1817)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1650)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1597)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1275)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1265)
	at android.content.pm.LauncherApps.getShortcutIconDrawable(LauncherApps.java:1316)
	at de.mm20.launcher2.search.data.LauncherShortcut$loadIcon$icon$1.invokeSuspend(LauncherShortcut.kt:24)
[7 lines truncated]
```

## Device info
APP.VERSION : 1.27.1<br>APP.VERSIONCODE : 2023090800<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/London<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : 2111252327<br>VERSION.SDK.NUMBER : 30<br>BOARD : sdm845<br>BOOTLOADER : unknown<br>BRAND : OnePlus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : ONEPLUS A6013_41_211125<br>FINGERPRINT : OnePlus/OnePlus6T/OnePlus6T:11/RKQ1.201217.002/2111252327:user/release-keys<br>HARDWARE : qcom<br>HOST : rd-build-72<br>ID : RKQ1.201217.002<br>MANUFACTURER : OnePlus<br>MODEL : ONEPLUS A6013<br>PRODUCT : OnePlus6T<br>TAGS : release-keys<br>TIME : 1637854373000<br>TYPE : user

**Comment by kud** [comment]
Actually it's worse. I don't know when it happens and it reboots all the phone.

**Comment by kud** [comment]
I don't know what's happening but I don't have any issue anymore and I did not change the version.

By any chance @dethmetaljeff do you use Firefox Nightly?

**Comment by dethmetaljeff** [comment]
Nope, just regular FF here.  I think the issue is with one of my contacts, I disabled contact search a bit ago and it hasn't been crashing on me.  I'll re-enable and see if I can reproduce the crash.

**Comment by kud** [comment]
I've updated some applications since I've created this ticket (not this launcher as no new version) and now the bug is gone. Weird.

**Comment by dethmetaljeff** [comment]
Yea, me too.... hasn't happened for awhile now.

**Comment by kud** [comment]
I don't know why but I feel either a widget did not respond (like weather or whater) and now it does, or maybe a "share" feature on a specific app is now fixed and does not break anymore the launcher. Let's close it so.
