### ISSUE TITLE
NullPointerError

### ISSUE THREAD

**Issue by dethmetaljeff** [MM2-0/Kvaesitso#547]
Crashes while searching.  Subsequent searches work fine.  

```
java.lang.NullPointerException
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3029)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1682)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1629)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1390)
	at android.content.pm.LauncherApps.getUriShortcutIconFd(LauncherApps.java:1380)
	at android.content.pm.LauncherApps.getShortcutIconDrawable(LauncherApps.java:1431)
	at de.mm20.launcher2.search.data.LauncherShortcut$loadIcon$icon$1.invokeSuspend(LauncherShortcut.kt:22)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:107)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:12)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:82)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@34ad9f0, Dispatchers.Main.immediate]

```

**Comment by dethmetaljeff** [comment]
Issue stopped happening, linked issue is closed as well.  Will reopen if it happens again.
