### ISSUE TITLE
Bug: backup filename causes crash

### ISSUE THREAD

**Issue by abonhote** [MM2-0/Kvaesitso#575]
The suggested filename contains colons. Without them, the file gets written properly.

`2023-10-14T11:00:08.367067Z.kvaesitso`

The crash log doesn't seem to help here:

```
java.io.FileNotFoundException: Not found > null
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:705)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1867)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1569)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1544)
	at de.mm20.launcher2.backup.BackupManager$backup$2.invokeSuspend(BackupManager.kt:107)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:112)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d4a9a55, Dispatchers.Main.immediate]

```

Samsung S23 Ultra, FWIW.

Awesome work by the way, just discovered it today. Just wow. Where's the donate button?

**Comment by abonhote** [comment]
Ah, found the donate thing 👍
