### ISSUE TITLE
Expression too large 

### ISSUE THREAD

**Issue by micahchoo** [MM2-0/Kvaesitso#587]
Launcher crashes when I search "Ani" consistently

**Comment by MM2-0** [comment]
Can you send the crash report? (Settings > Debug > crash reporter)

**Comment by micahchoo** [comment]
![Screenshot_2023-10-21-05-02-39-19_94226bc2e387a4f039bd6db013273604](https://github.com/MM2-0/Kvaesitso/assets/47268348/b36929f1-3fd2-436a-8213-cd2ff9e4f1b9)
Its the one from Oct 20. The other two crashes happened as I tried to open that crash report

**Comment by micahchoo** [comment]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: Can't represent a size of 621732 in Constraints
	at androidx.compose.ui.unit.Constraints$Companion.bitsNeedForSize(Constraints.kt:41)
	at androidx.compose.ui.unit.Constraints$Companion.createConstraints-Zbe2FdA$ui_unit_release(Constraints.kt:18)
	at androidx.compose.ui.unit.ConstraintsKt.Constraints(Constraints.kt:27)
	at androidx.compose.ui.unit.ConstraintsKt.Constraints$default(Constraints.kt:15)
	at kotlin.text.UStringsKt.finalConstraints-tfFHcEY(UStrings.kt:55)
	at androidx.compose.foundation.text.modifiers.ParagraphLayoutCache.layoutText-K40F9xA(ParagraphLayoutCache.kt:13)
	at androidx.compose.foundation.text.modifiers.TextStringSimpleNode.measure-3p2s80s(TextStringSimpleNode.kt:189)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator$LookaheadDelegateForLayoutModifierNode.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:27)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator$LookaheadDelegateForLayoutModifierNode.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:27)
	at androidx.compose.foundation.layout.PaddingNode.measure-3p2s80s(Padding.kt:33)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator$LookaheadDelegateForLayoutModifierNode.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:27)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performLookaheadMeasure$1.invoke(LayoutNodeLayoutDelegate.kt:16)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:59)
[150 lines truncated]
```

## Device info
APP.VERSION : 1.28.0<br>APP.VERSIONCODE : 2023101300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : America/Los_Angeles<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : Q.202307060216<br>VERSION.SDK.NUMBER : 31<br>BOARD : lito<br>BOOTLOADER : unknown<br>BRAND : OnePlus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : AC2001_11_F.21<br>FINGERPRINT : OnePlus/Nord_IND/Nord:12/RKQ1.211119.001/Q.202307060216:user/release-keys<br>HARDWARE : qcom<br>HOST : dg02-pool03-kvm77<br>ID : RKQ1.211119.001<br>MANUFACTURER : OnePlus<br>MODEL : AC2001<br>PRODUCT : Nord_IND<br>TAGS : release-keys<br>TIME : 1688630472000<br>TYPE : user




This is the log from the other 2 crashes

**Comment by MM2-0** [comment]
And it only happens with that specific search term?

**Comment by micahchoo** [comment]
Yup just that one, has happened before as well
