### ISSUE TITLE
Crash when opening integrations-page in settings

### ISSUE THREAD

**Issue by chefexperte** [MM2-0/Kvaesitso#630]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:20)
	at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:11)
	at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:6)
	at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:9)
	at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:1)
	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:30)
	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:1)
	at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:12)
	at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:48)
	at de.mm20.launcher2.owncloud.OwncloudClient.createPreferences(OwncloudClient.kt:21)
	at de.mm20.launcher2.owncloud.OwncloudClient.createPreferences(OwncloudClient.kt:44)
	at de.mm20.launcher2.owncloud.OwncloudClient$preferences$2.invoke(OwncloudClient.kt:4)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
	at de.mm20.launcher2.owncloud.OwncloudClient.getPreferences(OwncloudClient.kt:3)
[18 lines truncated]
```

## Device info
APP.VERSION : 1.28.0<br>APP.VERSIONCODE : 2023101300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 2023111500<br>VERSION.SDK.NUMBER : 34<br>BOARD : panther<br>BOOTLOADER : cloudripper-14.0-10529422<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231105.003.2023111500<br>FINGERPRINT : google/panther/panther:14/UP1A.231105.003/2023111500:user/release-keys<br>HARDWARE : panther<br>HOST : grapheneos<br>ID : UP1A.231105.003<br>MANUFACTURER : Google<br>MODEL : Pixel 7<br>PRODUCT : panther<br>TAGS : release-keys<br>TIME : 1700085706000<br>TYPE : user

**Comment by Ke1i** [comment]
Same here. It started happening after adding my self hosted owncloud instance (oCIS).
After being prompted for the login details when I supplied the owncloud server address in the integrations page, Kvaesitso crashed.
Now it keeps crashing when I open the integrations page inside settings.

## Strack trace

```
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:112)
	at org.json.JSONObject.<init>(JSONObject.java:169)
	at org.json.JSONObject.<init>(JSONObject.java:182)
	at de.mm20.launcher2.owncloud.OwncloudClient$getDisplayName$2.invokeSuspend(OwncloudClient.kt:14)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:112)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f03e242, Dispatchers.Main.immediate]

```

## Device info
APP.VERSION : 1.28.0<br>APP.VERSIONCODE : 2023101300<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Africa/Nairobi<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : eng.emy.20240108.024004<br>VERSION.SDK.NUMBER : 30<br>BOARD : MSM8974<br>BOOTLOADER : 3.19.0.0000<br>BRAND : htc<br>CPU_ABI : armeabi-v7a<br>CPU_ABI2 : armeabi<br>DISPLAY : RQ3A.211001.001<br>FINGERPRINT : htc/HTCOneM8vzw/htc_m8wl:6.0/MRA58K/708002.3:user/release-keys<br>HARDWARE : qcom<br>HOST : dosbm<br>ID : RQ3A.211001.001<br>MANUFACTURER : HTC<br>MODEL : m8wl<br>PRODUCT : lineage_m8<br>TAGS : release-keys<br>TIME : 1704699581000<br>TYPE : user
