### ISSUE TITLE
Shows crash report 

### ISSUE THREAD

**Issue by Sanjaycsk18** [MM2-0/Kvaesitso#647]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: node not yet measured
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree(MeasureAndLayoutDelegate.kt:49)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(MeasureAndLayoutDelegate.kt:46)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(MeasureAndLayoutDelegate.kt:125)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(MeasureAndLayoutDelegate.kt:125)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(MeasureAndLayoutDelegate.kt:125)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(MeasureAndLayoutDelegate.kt:125)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(MeasureAndLayoutDelegate.kt:125)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(MeasureAndLayoutDelegate.kt:125)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(MeasureAndLayoutDelegate.kt:125)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree(MeasureAndLayoutDelegate.kt:36)
	at androidx.compose.ui.platform.AndroidComposeView.forceMeasureTheSubtree(AndroidComposeView.android.kt:3)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:48)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:18)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureOnly(MeasureAndLayoutDelegate.kt:18)
[44 lines truncated]
```

## Device info
APP.VERSION : 1.28.0-fdroid<br>APP.VERSIONCODE : 2023101300<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 9<br>VERSION.INCREMENTAL : 16.2018.1905.44-20190522<br>VERSION.SDK.NUMBER : 28<br>BOARD : msm8953<br>BOOTLOADER : unknown<br>BRAND : asus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : OPM1.WW_Phone-16.2018.1905.44-20190522<br>FINGERPRINT : asus/WW_X01AD/ASUS_X01A_1:9/WW_Phone-201905221734/16.2018.1905.44-20190522:user/release-keys<br>HARDWARE : qcom<br>HOST : ubuntu<br>ID : WW_Phone-201905221734<br>MANUFACTURER : asus<br>MODEL : ASUS_X01AD<br>PRODUCT : WW_X01AD<br>TAGS : release-keys<br>TIME : 1558517805000<br>TYPE : user

**Comment by Sanjaycsk18** [comment]
I like this app
