### ISSUE TITLE
Crash when attempting to open a file stored on external SD card

### ISSUE THREAD

**Issue by craigh246** [MM2-0/Kvaesitso#66]
Launcher crashes when selecting a music file from search.

**Comment by craigh246** [comment]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/2722-0C1A/Music/Radiohead - OK Computer/02 - Paranoid Android.mp3
	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:825)
	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:450)
	at de.mm20.launcher2.search.data.LocalFile.getLaunchIntent(LocalFile.kt:135)
	at de.mm20.launcher2.search.data.Searchable.launch(Searchable.kt:25)
	at de.mm20.launcher2.ui.launcher.search.common.SearchableItemVM.launch(SearchableItemVM.kt:67)
	at de.mm20.launcher2.ui.launcher.search.common.list.ListItemKt$ListItem$2$2$5.invoke(ListItem.kt:149)
	at de.mm20.launcher2.ui.launcher.search.common.list.ListItemKt$ListItem$2$2$5.invoke(ListItem.kt:146)
	at androidx.compose.foundation.ClickableKt$combinedClickable$4$gesture$1$4.invoke-k-4lQ0M(Clickable.kt:339)
	at androidx.compose.foundation.ClickableKt$combinedClickable$4$gesture$1$4.invoke(Clickable.kt:318)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapGestures$2$1$1.invokeSuspend(TapGestureDetector.kt:125)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
[71 lines truncated]
```

## Device info
APP.VERSION : 1.9.0-20220417<br>APP.VERSIONCODE : 2022041700<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/London<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : A715FXXS8BVC1<br>VERSION.SDK.NUMBER : 30<br>BOARD : sm6150<br>BOOTLOADER : A715FXXS8BVC1<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : RP1A.200720.012.A715FXXS8BVC1<br>FINGERPRINT : samsung/a71naeea/a71:11/RP1A.200720.012/A715FXXS8BVC1:user/release-keys<br>HARDWARE : qcom<br>HOST : 21DJ7C14<br>ID : RP1A.200720.012<br>MANUFACTURER : samsung<br>MODEL : SM-A715F<br>PRODUCT : a71naeea<br>TAGS : release-keys<br>TIME : 1646637711000<br>TYPE : user

**Comment by MM2-0** [comment]
Seems to affect all files stored on external media. Thanks for the report.
