### ISSUE TITLE
SecurityException: Cannot get shortcuts for unrelated profile 0

### ISSUE THREAD

**Issue by doasu** [MM2-0/Kvaesitso#665]
## Description

Adding a shortcut/favourite app causes the launcher to crash when running on a non-primary Android user profile.
This happens automatically if you use an app often and it is added to the recent/frequent apps list.

## Strack trace

```
java.lang.SecurityException: Cannot get shortcuts for unrelated profile 0
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3066)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.content.pm.ILauncherApps$Stub$Proxy.getShortcuts(ILauncherApps.java:1117)
	at android.content.pm.LauncherApps.getShortcuts(LauncherApps.java:1227)
	at de.mm20.launcher2.appshortcuts.LauncherShortcutDeserializer.deserialize(AppShortcutSerialization.kt:163)
	at de.mm20.launcher2.searchable.SavableSearchableRepositoryImpl.fromDatabaseEntity(SavableSearchableRepository.kt:148)
	at de.mm20.launcher2.searchable.SavableSearchableRepositoryImpl$get$$inlined$map$1$2.emit(Emitters.kt:111)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:17)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:130)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
[21 lines truncated]
```

## Device info
APP.VERSION : 1.28.0-20240106-nightly<br>APP.VERSIONCODE : 2024010600<br>APP.SIGNATURE : wVhv3DbjVNC+HXuwkkmtXrdxWY8=<br>LAUNCHER.APP : de.mm20.launcher2.nightly<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 2024010400<br>VERSION.SDK.NUMBER : 34<br>BOARD : panther<br>BOOTLOADER : cloudripper-14.0-10825040<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UQ1A.240105.004.2024010400<br>FINGERPRINT : google/panther/panther:14/UQ1A.240105.004/2024010400:user/release-keys<br>HARDWARE : panther<br>HOST : grapheneos<br>ID : UQ1A.240105.004<br>MANUFACTURER : Google<br>MODEL : Pixel 7<br>PRODUCT : panther<br>TAGS : release-keys<br>TIME : 1704379447000<br>TYPE : user

**Comment by doasu** [comment]
Thank you!!! ^-^
