### ISSUE TITLE
Crash after click managed accounts

### ISSUE THREAD

**Issue by smartmanru** [MM2-0/Kvaesitso#71]
`
com.microsoft.identity.client.exception.MsalClientException: Intent filter for: BrowserTabActivity is missing.  Please make sure you have the following activity in your AndroidManifest.xml 

<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
	<intent-filter>
		<action android:name="android.intent.action.VIEW" />
		<category android:name="android.intent.category.DEFAULT" />
		<category android:name="android.intent.category.BROWSABLE" />
		<data
			android:host="de.mm20.launcher2.release"
			android:path="/rx1fSnL7r5/OMoFC0e1KPqTndXQ="
			android:scheme="msauth" />
	</intent-filter>
</activity>

	at com.microsoft.identity.client.PublicClientApplicationConfiguration.checkIntentFilterAddedToAppManifestForBrokerFlow(PublicClientApplicationConfiguration.java:591)
	at com.microsoft.identity.client.PublicClientApplication.initializeApplication(PublicClientApplication.java:1077)
	at com.microsoft.identity.client.PublicClientApplication.<init>(PublicClientApplication.java:1060)
	at com.microsoft.identity.client.SingleAccountPublicClientApplication.<init>(SingleAccountPublicClientApplication.java:95)
	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:941)
	at com.microsoft.identity.client.PublicClientApplication$9.onTaskCompleted(PublicClientApplication.java:929)
	at com.microsoft.identity.common.internal.controllers.CommandDispatcher.commandCallbackOnTaskCompleted(CommandDispatcher.java:448)
	at com.microsoft.identity.common.internal.controllers.CommandDispatcher.access$900(CommandDispatcher.java:83)
	at com.microsoft.identity.common.internal.controllers.CommandDispatcher$3.run(CommandDispatcher.java:427)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:241)
	at android.os.Looper.loop(Looper.java:358)
	at android.app.ActivityThread.main(ActivityThread.java:8005)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)`

APP.VERSION : 1.9.0-20220417
APP.VERSIONCODE : 2022041700
LAUNCHER.APP : android
TIMEZONE : Europe/Moscow
VERSION.RELEASE : 12
VERSION.INCREMENTAL : 31.1004.0404.81
VERSION.SDK.NUMBER : 31
BOARD : lahaina
BOOTLOADER : unknown
BRAND : asus
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : SKQ1.210821.001.31.1004.0404.81 release-keys
FINGERPRINT : asus/RU_I006D/ASUS_I006D:12/SKQ1.210821.001/31.1004.0404.81:user/release-keys
HARDWARE : qcom
HOST : builder2021-RS720-E9-RS8-G
ID : SKQ1.210821.001
MANUFACTURER : asus
MODEL : ZS590KS
PRODUCT : RU_I006D
TAGS : release-keys
TIME : 1641204792000
TYPE : user

**Comment by MM2-0** [comment]
I can't reproduce this. Could you provide some more details?

Are you using an official build of this app?
