### ISSUE TITLE
Launcher crashes and shows deadsystemexception error

### ISSUE THREAD

**Issue by Rek3n** [MM2-0/Kvaesitso#728]
## Description

The launcher crashes randomly and sometimes the pre-installed launcher crashes too even though it's not in use. 

## Strack trace

```
java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.ApplicationPackageManager.queryIntentActivitiesAsUser(ApplicationPackageManager.java:1280)
	at android.app.ApplicationPackageManager.queryIntentActivities(ApplicationPackageManager.java:1261)
	at de.mm20.launcher2.music.MusicServiceImpl$getInstalledPlayerPackages$2.invokeSuspend(MusicService.kt:27)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:96)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@60ef0b9, Dispatchers.Default]
Caused by: android.os.DeadSystemException
	... 8 more

```

## Device info
APP.VERSION : 1.29.1<br>APP.VERSIONCODE : 2024022100<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Asia/Kolkata<br>VERSION.RELEASE : 12<br>VERSION.INCREMENTAL : 1591b-5bf47<br>VERSION.SDK.NUMBER : 31<br>BOARD : hanoip<br>BOOTLOADER : MBM-3.0-hanoip_retail-9522caba9cf-230725<br>BRAND : motorola<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : S2RI32.32-20-9-9-2<br>FINGERPRINT : motorola/hanoip_retail/hanoip:12/S2RI32.32-20-9-9-2/1591b-5bf47:user/release-keys<br>HARDWARE : qcom<br>HOST : ilclbld186<br>ID : S2RI32.32-20-9-9-2<br>MANUFACTURER : motorola<br>MODEL : moto g(40) fusion<br>PRODUCT : hanoip_retail<br>TAGS : release-keys<br>TIME : 1690301047000<br>TYPE : user

**Comment by Sir-Photch** [comment]
A quick websearch reveals:

> The core Android system has died and is going through a runtime restart. All running apps will be promptly killed.

This suggests that it is not an issue of Kvaesitso. It also explains why your default launcher crashes.

https://developer.android.com/reference/android/os/DeadSystemException.html

**Comment by MM2-0** [comment]
:skull:
