### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by myxor** [MM2-0/Kvaesitso#74]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.NullPointerException: Attempt to read from field 'int com.android.server.wm.Task.mTaskId' on a null object reference
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.content.pm.ILauncherApps$Stub$Proxy.startActivityAsUser(ILauncherApps.java:1146)
	at android.content.pm.LauncherApps.startMainActivity(LauncherApps.java:745)
	at de.mm20.launcher2.search.data.LauncherApp.launch(LauncherApp.kt:78)
	at de.mm20.launcher2.ui.launcher.search.common.SearchableItemVM.launch(SearchableItemVM.kt:67)
	at de.mm20.launcher2.ui.launcher.search.common.GridItemKt$GridItem$1$2.invoke(GridItem.kt:70)
	at de.mm20.launcher2.ui.launcher.search.common.GridItemKt$GridItem$1$2.invoke(GridItem.kt:61)
	at de.mm20.launcher2.ui.component.ShapedLauncherIconKt$ShapedLauncherIcon$1$2$1.invoke(ShapedLauncherIcon.kt:65)
	at de.mm20.launcher2.ui.component.ShapedLauncherIconKt$ShapedLauncherIcon$1$2$1.invoke(ShapedLauncherIcon.kt:64)
	at androidx.compose.foundation.ClickableKt$combinedClickable$4$gesture$1$4.invoke-k-4lQ0M(Clickable.kt:339)
	at androidx.compose.foundation.ClickableKt$combinedClickable$4$gesture$1$4.invoke(Clickable.kt:318)
[81 lines truncated]
```

## Device info
APP.VERSION : 1.9.0-20220417<br>APP.VERSIONCODE : 2022041700<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : eng.root.20220319.091411<br>VERSION.SDK.NUMBER : 30<br>BOARD : sdm660<br>BOOTLOADER : unknown<br>BRAND : Xiaomi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : lineage_lavender-userdebug 11 RQ3A.211001.001 eng.root.20220319.091411 dev-keys<br>FINGERPRINT : xiaomi/lavender/lavender:10/QKQ1.190910.002/V12.5.3.0.QFGCNXM:user/release-keys<br>HARDWARE : qcom<br>HOST : 4005af6db1c4<br>ID : RQ3A.211001.001<br>MANUFACTURER : Xiaomi<br>MODEL : Redmi Note 7<br>PRODUCT : lineage_lavender<br>TAGS : dev-keys<br>TIME : 1647681114000<br>TYPE : userdebug

**Comment by MM2-0** [comment]
Could you provide some more information? Does it crash every time you launch that app or does it happen randomly? Which app are you attempting to start? Are you starting the app as main user or in a work profile?

**Comment by myxor** [comment]
It only happened once and i can not remember which app i launched as this happened.
Sorry that i can not provide any more information.
