### ISSUE TITLE
The bottom overlay to adjust widget and to rename apps crashes 

### ISSUE THREAD

**Issue by Bhardwaj10Ankit** [MM2-0/Kvaesitso#750]
##+Description

*Please+provide+as+many+information+about+the+crash+as+possible+(What+did+you+do+before+the+crash+happened?+Steps+to+reproduce?)*

##+Strack+trace

```
com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException:+Protocol+message+contained+an+invalid+tag+(zero).
	at+com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:20)
	at+com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:11)
	at+com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:6)
	at+com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:9)
	at+com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:1)
	at+com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:30)
	at+com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:1)
	at+com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:15)
	at+androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:48)
	at+de.mm20.launcher2.owncloud.OwncloudClient.createPreferences(OwncloudClient.kt:21)
	at+de.mm20.launcher2.owncloud.OwncloudClient.createPreferences(OwncloudClient.kt:44)
	at+de.mm20.launcher2.owncloud.OwncloudClient$preferences$2.invoke(OwncloudClient.kt:4)
	at+kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:21)
	at+de.mm20.launcher2.owncloud.OwncloudClient.getPreferences(OwncloudClient.kt:3)
[30+lines+truncated]
```
And also this 

```
java.lang.IllegalStateException: DeferredCoroutine was cancelled
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3065)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
	at android.content.ContentResolver.query(ContentResolver.java:1231)
	at de.mm20.launcher2.files.providers.PluginFileProvider$search$2.invokeSuspend(PluginFileProvider.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)


```
##+Device+info
APP.VERSION+:+1.29.1-20240401-nightly<br>APP.VERSIONCODE+:+2024040100<br>APP.SIGNATURE+:+wVhv3DbjVNC+HXuwkkmtXrdxWY8=<br>LAUNCHER.APP+:+de.mm20.launcher2.nightly<br>TIMEZONE+:+Asia/Calcutta<br>VERSION.RELEASE+:+14<br>VERSION.INCREMENTAL+:+2401161446<br>VERSION.SDK.NUMBER+:+34<br>BOARD+:+taro<br>BOOTLOADER+:+00979.4-WAIPIO-1<br>BRAND+:+Nothing<br>CPU_ABI+:+arm64-v8a<br>CPU_ABI2+:+<br>DISPLAY+:+U2.5-240116-1446<br>FINGERPRINT+:+Nothing/PongIND/Pong:14/UP1A.231005.007/2401161446:user/release-keys<br>HARDWARE+:+qcom<br>HOST+:+nothing<br>ID+:+UP1A.231005.007<br>MANUFACTURER+:+Nothing<br>MODEL+:+AIN065<br>PRODUCT+:+PongIND<br>TAGS+:+release-keys<br>TIME+:+1705387571000<br>TYPE+:+user

**Comment by Bhardwaj10Ankit** [comment]
@MM2-0 , 🙏🏻 thanks for fixing this.
