### ISSUE TITLE
[Bug] No apps under favorites, recent, or tags on GrapheneOS

### ISSUE THREAD

**Issue by Netpilgrim** [MM2-0/Kvaesitso#787]
On GrapheneOS I can’t mark apps as favorite; the favorite icon doesn’t change and the app isn’t added to the favorites section. Recently used apps aren’t shown there either. And while I can add tags to apps and those tags appear in that section, when selected no tagged apps are shown. Otherwise the app search works as expected. Reboot or reinstall doesn’t help.

I’ve used Kvaesitso with Android versions by Samsung and Google before without issues. From what I’ve found it usually seems to work fine on GrapheneOS, too.

Kvaesitso version: 1.29.1, installed via Neo Store from the MM20 Apps repository
OS version: GrapheneOS 2024042200 (Android 14)
Device: Pixel 8

**Comment by derei** [comment]
I just installed Kvaesitso on Pixel 7Pro, running GrapheneOS. I had no issues of the kind you are describing.
Just to be clear: I am not saying this to invalidate your experience, but to point our there may be another variable and it may be worth investigating deeper, to see what exactly is the root cause.

**Comment by exstntlmsnthrp** [comment]
The latest app version is 1.30.4. Try updating and it may fix the issue.

**Comment by Netpilgrim** [comment]
Sorry for not getting back to this earlier. I’ve tried again with Kvaesitso 1.30.4 on GrapheneOS build 2024053100 and the problem still persists for me. The log shows the following exception, when trying to mark an app as favorite (in this case the camera app):

```
06-03 06:09:57.696 14593 14593 E MM20    : Failed to deserialize app: {"package":"app.grapheneos.camera","activity":"app.grapheneos.camera.ui.activities.MainActivity","user":0}
06-03 06:09:57.696 14593 14593 E MM20    : java.lang.SecurityException: Cannot resolve activity for unrelated profile 0
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3191)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.os.Parcel.createException(Parcel.java:3175)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.os.Parcel.readException(Parcel.java:3151)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.os.Parcel.readException(Parcel.java:3093)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.content.pm.ILauncherApps$Stub$Proxy.resolveLauncherActivityInternal(ILauncherApps.java:969)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.content.pm.LauncherApps.resolveActivity(LauncherApps.java:885)
06-03 06:09:57.696 14593 14593 E MM20    : 	at de.mm20.launcher2.applications.LauncherAppDeserializer.deserialize(AppSerialization.kt:69)
06-03 06:09:57.696 14593 14593 E MM20    : 	at de.mm20.launcher2.searchable.SavableSearchableRepositoryImpl.fromDatabaseEntity(SavableSearchableRepository.kt:148)
06-03 06:09:57.696 14593 14593 E MM20    : 	at de.mm20.launcher2.searchable.SavableSearchableRepositoryImpl$get$$inlined$map$1$2.emit(Emitters.kt:111)
06-03 06:09:57.696 14593 14593 E MM20    : 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:5)
06-03 06:09:57.696 14593 14593 E MM20    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:17)
06-03 06:09:57.696 14593 14593 E MM20    : 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
06-03 06:09:57.696 14593 14593 E MM20    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:129)
06-03 06:09:57.696 14593 14593 E MM20    : 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
06-03 06:09:57.696 14593 14593 E MM20    : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
06-03 06:09:57.696 14593 14593 E MM20    : 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.os.Handler.handleCallback(Handler.java:959)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.os.Looper.loopOnce(Looper.java:232)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.os.Looper.loop(Looper.java:317)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.app.ActivityThread.main(ActivityThread.java:8532)
06-03 06:09:57.696 14593 14593 E MM20    : 	at java.lang.reflect.Method.invoke(Native Method)
06-03 06:09:57.696 14593 14593 E MM20    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
06-03 06:09:57.696 14593 14593 E MM20    : 	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
06-03 06:09:57.696 14593 14593 E MM20    : 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
06-03 06:09:57.696 14593 14593 E MM20    : 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
06-03 06:09:57.696 14593 14593 E MM20    : Caused by: android.os.RemoteException: Remote stack trace:
06-03 06:09:57.696 14593 14593 E MM20    : 	at com.android.server.pm.UserManagerService$LocalService.isProfileAccessible(UserManagerService.java:7287)
06-03 06:09:57.696 14593 14593 E MM20    : 	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.canAccessProfile(LauncherAppsService.java:464)
06-03 06:09:57.696 14593 14593 E MM20    : 	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.canAccessProfile(LauncherAppsService.java:440)
06-03 06:09:57.696 14593 14593 E MM20    : 	at com.android.server.pm.LauncherAppsService$LauncherAppsImpl.resolveLauncherActivityInternal(LauncherAppsService.java:684)
06-03 06:09:57.696 14593 14593 E MM20    : 	at android.content.pm.ILauncherApps$Stub.onTransact(ILauncherApps.java:400)
```

**Comment by Netpilgrim** [comment]
This problem does not occur when running Kvaesitso in the “Owner” profile (primary admin account).
A similar problem was apparently addressed in #301.

**Comment by dotslashme** [comment]
I'm seeing the same behavior with the following configuration

Pixel 6
GrapheneOS build 2024060500
Kvaesito version 1.30.4 installed in secondary profile 
from the github releases using Obtainium.

[log.txt](https://github.com/user-attachments/files/15808320/log.txt)
