### ISSUE TITLE
Crashes after accessing app shortcuts

### ISSUE THREAD

**Issue by efonekpo** [MM2-0/Kvaesitso#796]
## Description

After long clicking on an app to bring up the app short cuts, I click on one of the shortcuts and it takes me to the app. Upon returning back to the launcher, that's when it crashes. It has happened a lot of times now without fail.

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.8146972E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.InlineClassHelperKt.throwIllegalArgumentException(InlineClassHelper.kt:3)
	at androidx.compose.ui.graphics.ColorKt.Color(Color.kt:17)
	at androidx.compose.ui.graphics.Color.copy-wmQWz5c$default(Color.kt:17)
	at de.mm20.launcher2.ui.launcher.search.common.grid.GridItemKt$ItemPopup$3.invoke(GridItem.kt:54)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:7)
	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:585)
	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:137)
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:242)
	at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:30)
	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:21)
	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:77)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:545)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
[15 lines truncated]
```

## Device info
APP.VERSION : 1.30.0<br>APP.VERSIONCODE : 2024050700<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : America/Los_Angeles<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : S918U1UES2CXCN<br>VERSION.SDK.NUMBER : 34<br>BOARD : kalama<br>BOOTLOADER : S918U1UES2CXCN<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.S918U1UES2CXCN<br>FINGERPRINT : samsung/dm3quew/dm3q:14/UP1A.231005.007/S918U1UES2CXCN:user/release-keys<br>HARDWARE : qcom<br>HOST : 21DK7915<br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-S918U1<br>PRODUCT : dm3quew<br>TAGS : release-keys<br>TIME : 1712132898000<br>TYPE : user

**Comment by MM2-0** [comment]
Does this issue still occur on the latest version?

**Comment by efonekpo** [comment]
The issue has been resolved with the latest update
