### ISSUE TITLE
Crash opening hiden apps

### ISSUE THREAD

**Issue by inv1sibleYT** [MM2-0/Kvaesitso#809]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.NullPointerException: Attempt to read from field 'androidx.compose.ui.node.LayoutNodeLayoutDelegate androidx.compose.ui.node.LayoutNode.layoutDelegate' on a null object reference in method 'void androidx.compose.ui.node.LayoutNode.onChildRemoved(androidx.compose.ui.node.LayoutNode)'
	at androidx.compose.ui.node.LayoutNode.onChildRemoved(LayoutNode.kt:1)
	at androidx.compose.ui.node.LayoutNode.removeAt$ui_release(LayoutNode.kt:18)
	at androidx.compose.ui.node.UiApplier.remove(UiApplier.android.kt:5)
	at androidx.compose.runtime.changelist.Operation$RemoveNode.execute(Operation.kt:11)
	at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:23)
	at androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges(ChangeList.kt:3)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:51)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:6)
	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:217)
	at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:7)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:48)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1232)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1242)
	at android.view.Choreographer.doCallbacks(Choreographer.java:902)
[12 lines truncated]
```

**Comment by MM2-0** [comment]
Fixed in 1.30.2
