### ISSUE TITLE
IllegalStateException: Offset is unspecified

### ISSUE THREAD

**Issue by labrusca** [MM2-0/Kvaesitso#81]
version 1.10.1
Don't know why
```
java.lang.IllegalStateException: Offset is unspecified
	at androidx.compose.ui.geometry.Offset.getX-impl(Offset.kt:67)
	at androidx.compose.ui.unit.IntOffsetKt.minus-Nv-tHpc(IntOffset.kt:165)
	at androidx.compose.ui.node.LayoutNodeWrapper.fromParentPosition-MK-Hz9U(LayoutNodeWrapper.kt:790)
	at androidx.compose.ui.node.LayoutNodeWrapper.ancestorToLocal-R5De75A(LayoutNodeWrapper.kt:741)
	at androidx.compose.ui.node.LayoutNodeWrapper.ancestorToLocal-R5De75A(LayoutNodeWrapper.kt:741)
	at androidx.compose.ui.node.LayoutNodeWrapper.ancestorToLocal-R5De75A(LayoutNodeWrapper.kt:741)
	at androidx.compose.ui.node.LayoutNodeWrapper.ancestorToLocal-R5De75A(LayoutNodeWrapper.kt:741)
	at androidx.compose.ui.node.LayoutNodeWrapper.ancestorToLocal-R5De75A(LayoutNodeWrapper.kt:741)
	at androidx.compose.ui.node.LayoutNodeWrapper.ancestorToLocal-R5De75A(LayoutNodeWrapper.kt:741)
	at androidx.compose.ui.node.LayoutNodeWrapper.ancestorToLocal-R5De75A(LayoutNodeWrapper.kt:741)
	at androidx.compose.ui.node.LayoutNodeWrapper.ancestorToLocal-R5De75A(LayoutNodeWrapper.kt:741)
	at androidx.compose.ui.node.LayoutNodeWrapper.ancestorToLocal-R5De75A(LayoutNodeWrapper.kt:741)
	at androidx.compose.ui.node.LayoutNodeWrapper.localPositionOf-R5De75A(LayoutNodeWrapper.kt:699)
	at androidx.compose.ui.input.pointer.Node.buildCache(HitPathTracker.kt:377)
	at androidx.compose.ui.input.pointer.NodeParent.buildCache(HitPathTracker.kt:149)
	at androidx.compose.ui.input.pointer.Node.buildCache(HitPathTracker.kt:353)
	at androidx.compose.ui.input.pointer.NodeParent.buildCache(HitPathTracker.kt:149)
	at androidx.compose.ui.input.pointer.Node.buildCache(HitPathTracker.kt:353)
	at androidx.compose.ui.input.pointer.NodeParent.buildCache(HitPathTracker.kt:149)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:89)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:80)
	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1261)
	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1211)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1150)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3169)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2845)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:573)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1911)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4256)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:521)
	at android.view.View.dispatchPointerEvent(View.java:14899)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6749)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6520)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5989)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6051)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6012)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6186)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6020)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6243)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5993)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6051)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6012)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6020)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5993)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9028)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8979)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8935)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9171)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:266)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:246)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9116)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9257)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1228)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1025)
	at android.view.Choreographer.doFrame(Choreographer.java:914)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1213)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8210)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

**Comment by Relwi** [comment]
I think I had the same problem, it happened to me when I was playing with the notification bar, in some point I was trying to pull down the notification bar when it was hidding, but I'm not sure 100%

**Comment by xiaoyinliuyun** [comment]
`Modifier.graphicsLayer {
                            if (itemInfo.rotationX
                                    .isNaN()
                                    .not()
                            ) {
                                this.rotationX = itemInfo.rotationX
                            }
                        }`

**Comment by MM2-0** [comment]
Fixed in upstream library: https://android-review.googlesource.com/c/platform/frameworks/support/+/2475105
