### ISSUE TITLE
Application crashes after clearing background apps

### ISSUE THREAD

**Issue by Gromate** [MM2-0/Kvaesitso#858]
# Description 
Application crashes after clearing out all working application. 

## Reproduction
- On home page click Overview button (to show recent apps)
- Clear out all recent apps
- Kvaesitso stays opened (as it should) phone goes back to main page
- Now when you try to use search bar or scroll down application crashes

# Stack trace
```java
android.view.InflateException: Class not found foreground
	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:224)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:141)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1402)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1391)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1378)
	at de.mm20.launcher2.icons.compat.AdaptiveIconDrawableCompat$Companion.parseLayer(AdaptiveIconDrawableCompat.kt:27)
	at de.mm20.launcher2.icons.compat.AdaptiveIconDrawableCompat$Companion.from(AdaptiveIconDrawableCompat.kt:21)
	at de.mm20.launcher2.icons.providers.CompatIconProvider$getIcon$icon$1.invokeSuspend(CompatIconProvider.kt:44)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
Caused by: java.lang.ClassNotFoundException: Didn't find class "foreground" on path: DexPathList[[zip file "/data/app/de.mm20.launcher2.release-eni2PNIgXp2p3QhXLtKk7g==/base.apk"],nativeLibraryDirectories=[/data/app/de.mm20.launcher2.release-eni2PNIgXp2p3QhXLtKk7g==/lib/arm64, /data/app/de.mm20.launcher2.release-eni2PNIgXp2p3QhXLtKk7g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.graphics.drawable.DrawableInflater.inflateFromClass(DrawableInflater.java:205)
	... 12 more
```
# Specification
```
APP.VERSION : 1.30.4
APP.VERSIONCODE : 2024051000
APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=
LAUNCHER.APP : de.mm20.launcher2.release
TIMEZONE : Europe/Warsaw
VERSION.RELEASE : 10
VERSION.INCREMENTAL : V12.0.3.0.QDTMIXM
VERSION.SDK.NUMBER : 29
BOARD : sdm660
BOOTLOADER : unknown
BRAND : Xiaomi
CPU_ABI : arm64-v8a
CPU_ABI2 : 
DISPLAY : QKQ1.190910.002 test-keys
FINGERPRINT : Xiaomi/platina/platina:10/QKQ1.190910.002/V12.0.3.0.QDTMIXM:user/release-keys
HARDWARE : qcom
HOST : c5-miui-ota-bd148.bj
ID : QKQ1.190910.002
MANUFACTURER : Xiaomi
MODEL : MI 8 Lite
PRODUCT : platina
TAGS : release-keys
TIME : 1600080787000
TYPE : user
```

**Comment by exstntlmsnthrp** [comment]
Are you using the three button navigation or gesture navigation? 

I only ask because I cannot duplicate this problem with gesture navigation enabled.

**Comment by Gromate** [comment]
I'm using button navigation and it crashes every time, I imagine that it might be related to some MIUI problems.

**Comment by exstntlmsnthrp** [comment]
I don't know if it's a MIUI problem. I'm not an Android developer, but it looks like it's calling for a ```Class``` that doesn't exist and giving this error.
