### ISSUE TITLE
Launcher crashes after i open any app

### ISSUE THREAD

**Issue by Matytoonist** [MM2-0/Kvaesitso#867]
## Description

As stated in the title, the launcher crashes after opening any app, cheching the app history/apps in running background.

This started happening after updating to the latest version.

## Strack trace

```
java.lang.IllegalStateException: The display list is not valid.
	at android.view.RenderNode.getNativeDisplayList(RenderNode.java:260)
	at android.view.DisplayListCanvas.drawRenderNode(DisplayListCanvas.java:189)
	at androidx.compose.ui.graphics.layer.GraphicsLayerV23.draw(GraphicsLayerV23.android.kt:28)
	at androidx.compose.ui.graphics.layer.LayerManager.persistLayers(LayerManager.android.kt:59)
	at androidx.compose.ui.graphics.AndroidGraphicsContext$componentCallback$1.onTrimMemory(AndroidGraphicsContext.android.kt:21)
	at android.app.Application.onTrimMemory(Application.java:136)
	at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5356)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1799)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6543)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
[1 lines truncated]
```

## Device info
APP.VERSION : 1.30.3<br>APP.VERSIONCODE : 2024050900<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : com.sec.android.app.launcher<br>TIMEZONE : America/Argentina/Buenos_Aires<br>VERSION.RELEASE : 8.1.0<br>VERSION.INCREMENTAL : J260MUBSDAUJ1<br>VERSION.SDK.NUMBER : 27<br>BOARD : universal7570_go<br>BOOTLOADER : J260MUBSDAUJ1<br>BRAND : samsung<br>CPU_ABI : armeabi-v7a<br>CPU_ABI2 : armeabi<br>DISPLAY : M1AJB.J260MUBSDAUJ1<br>FINGERPRINT : samsung/j2corelteub/j2corelte:8.1.0/M1AJB/J260MUBSDAUJ1:user/release-keys<br>HARDWARE : samsungexynos7570<br>HOST : SWDH4603<br>ID : M1AJB<br>MANUFACTURER : samsung<br>MODEL : SM-J260M<br>PRODUCT : j2corelteub<br>TAGS : release-keys<br>TIME : 1634904683000<br>TYPE : user

**Comment by exstntlmsnthrp** [comment]
As pointed out in the information you shared above....

```
Device info
APP.VERSION : 1.30.3
APP.VERSIONCODE : 2024050900
APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=
LAUNCHER.APP : com.sec.android.app.launcher
```

That is a different launcher causing those problems, likely the default launcher. If it were kvaesitso, it would look like the following...

```
LAUNCHER.APP : de.mm20.launcher2.release
```

Furthermore, you're using Android version 8, which is more likely the cause of some problems. That is a six, nearly seven, year old version of Android with many bugs and security vulnerabilities and will likely not be supported by kvaesitso after Android 15 is released later this summer.
