### ISSUE TITLE
Full screen clock was gone and crash happened upon opening logs

### ISSUE THREAD

**Issue by lolpowerluke** [MM2-0/Kvaesitso#872]
## Description

Closed an app like I always do
Saw clock widget wasn't there
Opened logs
Crash

## Strack trace

```
java.lang.IndexOutOfBoundsException: Index 7, size 7
	at androidx.compose.foundation.lazy.layout.MutableIntervalList.checkIndexBounds(IntervalList.kt:27)
	at androidx.compose.foundation.lazy.layout.MutableIntervalList.get(IntervalList.kt:1)
	at androidx.compose.foundation.lazy.layout.LazyLayoutIntervalContent.getKey(LazyLayoutIntervalContent.kt:5)
	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.getKey(LazyListItemProvider.kt:11)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:18)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:15)
	at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-x0Ok8Vo(LazyListMeasure.kt:24)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:533)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:21)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:74)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:50)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:189)
	at androidx.compose.foundation.layout.PaddingValuesModifier.measure-3p2s80s(Padding.kt:115)
[94 lines truncated]
```

## Device info
APP.VERSION : 1.30.4<br>APP.VERSIONCODE : 2024051000<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Brussels<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 11677807<br>VERSION.SDK.NUMBER : 34<br>BOARD : panther<br>BOOTLOADER : cloudripper-14.4-11458464<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : AP1A.240505.005<br>FINGERPRINT : google/panther/panther:14/AP1A.240505.005/11677807:user/release-keys<br>HARDWARE : panther<br>HOST : r-bef26f36bea6bbb5-4gpb<br>ID : AP1A.240505.005<br>MANUFACTURER : Google<br>MODEL : Pixel 7<br>PRODUCT : panther<br>TAGS : release-keys<br>TIME : 1712337953000<br>TYPE : user

**Comment by lolpowerluke** [comment]
This also happened right before I updated to 1.30.4 (from 1.29.1)

**Comment by lolpowerluke** [comment]
This log should contain the error for the clock
https://cdn.discordapp.com/attachments/773629040187146241/1247305396746715186/kvaesitso-log-2024-06-03-234132?ex=665f8b2c&is=665e39ac&hm=7b5ed2cd2d559c3dd6ff6253a892ed72985d9dab7f5f891af930f3e430472446
