### ISSUE TITLE
IndexOutOfBoundsException in androidx.navigation.compose.NavHostKt

### ISSUE THREAD

**Issue by bannus** [MM2-0/Kvaesitso#888]
## Description

Sorry, not sure what I was doing that made this happen. Passing along the stack in case it's helpful 

## Strack trace

```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.get(ArrayList.java:434)
	at androidx.navigation.compose.NavHostKt$NavHost$20$1.invokeSuspend(NavHost.kt:45)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
[6 lines truncated]
```

## Device info
APP.VERSION : 1.30.4<br>APP.VERSIONCODE : 2024051000<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : America/New_York<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : S901U1UES5EXE3<br>VERSION.SDK.NUMBER : 34<br>BOARD : taro<br>BOOTLOADER : S901U1UES5EXE3<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.S901U1UES5EXE3<br>FINGERPRINT : samsung/r0quew/r0q:14/UP1A.231005.007/S901U1UES5EXE3:user/release-keys<br>HARDWARE : qcom<br>HOST : SWDK6607<br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-S901U1<br>PRODUCT : r0quew<br>TAGS : release-keys<br>TIME : 1716878782000<br>TYPE : user

**Comment by fegan104** [comment]
This can probably be closed since the [activity dependency was updated to 1.9.2](https://github.com/MM2-0/Kvaesitso/commit/d745d199aae5b50ed471325c2651211a3e3ec005#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR29) a few weeks ago. If that hasn't fixed it you can try [updating to activity 1.9.3](https://developer.android.com/jetpack/androidx/releases/activity#1.9.3). Thwere are some more details on this bug documented on [Google issue tracker](https://issuetracker.google.com/issues/340202286)
