### ISSUE TITLE
Crash after sluggish behaviour

### ISSUE THREAD

**Issue by sig11b** [MM2-0/Kvaesitso#897]
## Description

I wasn't doing anything unusual. But I did notice sluggish behaviour and slow responses before the crash. 

Sorry that I can't be more helpful, but since I like this launcher, I want to give feedback :)

## Strack trace

```
java.lang.OutOfMemoryError: Failed to allocate a 80 byte allocation with 2333536 free bytes and 2278KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.getMatrix-sQKQjiQ(GraphicsLayerOwnerLayer.android.kt:49)
	at androidx.compose.ui.platform.GraphicsLayerOwnerLayer.mapBounds(GraphicsLayerOwnerLayer.android.kt:23)
	at androidx.compose.ui.node.NodeCoordinator.rectInParent$ui_release(NodeCoordinator.kt:74)
	at androidx.compose.ui.node.NodeCoordinator.localBoundingBoxOf(NodeCoordinator.kt:79)
	at androidx.compose.ui.layout.LayoutCoordinatesKt.boundsInWindow(LayoutCoordinates.kt:31)
	at de.mm20.launcher2.ui.launcher.search.common.grid.GridItemKt$GridItem$6$2$1$1.invoke(GridItem.kt:8)
	at androidx.compose.ui.layout.OnGloballyPositionedNode.onGloballyPositioned(OnGloballyPositionedModifier.kt:3)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:66)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
	at androidx.compose.ui.node.OnPositionedDispatcher.dispatchHierarchy(OnPositionedDispatcher.kt:153)
[48 lines truncated]
```

## Device info
APP.VERSION : 1.30.4<br>APP.VERSIONCODE : 2024051000<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : V816.0.3.0.UKOEUXM<br>VERSION.SDK.NUMBER : 34<br>BOARD : lisa<br>BOOTLOADER : unknown<br>BRAND : Xiaomi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UKQ1.231108.001 release-keys<br>FINGERPRINT : Xiaomi/lisa_eea/lisa:14/UKQ1.231108.001/V816.0.3.0.UKOEUXM:user/release-keys<br>HARDWARE : qcom<br>HOST : pangu-build-component-system-276761-xfxvs-pvcs3-x79bz<br>ID : UKQ1.231108.001<br>MANUFACTURER : Xiaomi<br>MODEL : 2109119DG<br>PRODUCT : lisa_eea<br>TAGS : release-keys<br>TIME : 1710251298000<br>TYPE : user

**Comment by sig11b** [comment]
I just noticed: it may be the same as #885 or #823 or #825

**Comment by MM2-0** [comment]
I think this was an issue in a library and has been fixed since.
https://issuetracker.google.com/issues/336167334

Feel free to reopen if this occurs again on 1.31.x
