### ISSUE TITLE
java.lang.IllegalArgumentException: Error: Uninitialized LayoutCoordinates. Please make sure when using the SharedTransitionScope composable function, the modifier passed to the child content is being used, or use SharedTransitionLayout instead.

### ISSUE THREAD

**Issue by mr-c** [MM2-0/Kvaesitso#925]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

## Strack trace

```
java.lang.IllegalArgumentException: Error: Uninitialized LayoutCoordinates. Please make sure when using the SharedTransitionScope composable function, the modifier passed to the child content is being used, or use SharedTransitionLayout instead.
	at androidx.compose.animation.SharedBoundsNode$measure$1.invoke(SharedContentNode.kt:73)
	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(LookaheadDelegate.kt:7)
	at androidx.compose.ui.node.LookaheadDelegate.placeChildren(LookaheadDelegate.kt:5)
	at androidx.compose.ui.node.LookaheadDelegate.placeAt-f8xVGno(LookaheadDelegate.kt:9)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:15)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate$placeSelf$2.invoke(LayoutNodeLayoutDelegate.kt:60)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:114)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.placeSelf-MLgxB_4$1(LayoutNodeLayoutDelegate.kt:104)
	at androidx.compose.ui.node.LayoutNode.lookaheadReplace$ui_release(LayoutNode.kt:35)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:41)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:44)
[19 lines truncated]
```

## Device info
APP.VERSION : 1.31.1<br>APP.VERSIONCODE : 2024070100<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 13<br>VERSION.INCREMENTAL : TT4H<br>VERSION.SDK.NUMBER : 33<br>BOARD : FP5<br>BOOTLOADER : unknown<br>BRAND : Fairphone<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : FP5.TT4H.A.162.20240609<br>FINGERPRINT : Fairphone/FP5/FP5:13/TKQ1.230127.002/TT4H:user/release-keys<br>HARDWARE : qcom<br>HOST : T2M-NB-SW-T2<br>ID : TKQ1.230127.002<br>MANUFACTURER : Fairphone<br>MODEL : FP5<br>PRODUCT : FP5<br>TAGS : release-keys<br>TIME : 1717926672000<br>TYPE : user

**Comment by MM2-0** [comment]
Outdated version, should he fixed in 1.31.2
