### ISSUE TITLE
Incomplete Icons

### ISSUE THREAD

**Issue by funnie-monkey** [MM2-0/Kvaesitso#926]
Got a Google Pixel 8 Pro

Changed Icon pack to one from Icon Pack Studio and noticed that sometimes Icons weren't complete. Thought it was because icon packs from IPS weren't tested on Kvaesitso, so I changed it back to system icons and the problem is still there.

![1000001939](https://github.com/MM2-0/Kvaesitso/assets/41880357/6036e4a1-74d1-4128-bb77-337f8035d197)
![Screenshot_20240705-202826](https://github.com/MM2-0/Kvaesitso/assets/41880357/d66309f5-be4b-43d1-b611-a65f6552f9e8)

**Comment by exstntlmsnthrp** [comment]
Have you tried rebuilding the icon pack cache? It's found under ```Settings > Debug > Reinstall Icon Packs```.

**Comment by funnie-monkey** [comment]
> Have you tried rebuilding the icon pack cache? It's found under `Settings > Debug > Reinstall Icon Packs`.

It's only a temporary fix for me. When I do it, it fixes the messed up icons, but once I lock the phone and unlock it, I still get messed up icons. I also noticed that in the crash reporter I get:

```
java.io.FileNotFoundException: appfilter.xml
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:917)
	at android.content.res.AssetManager.open(AssetManager.java:894)
	at de.mm20.launcher2.icons.loaders.AppFilterIconPackInstaller.getAppfilterParser(AppFilterIconPackInstaller.kt:94)
	at de.mm20.launcher2.icons.loaders.AppFilterIconPackInstaller.access$parseAppfilterXml(AppFilterIconPackInstaller.kt:185)
	at de.mm20.launcher2.icons.loaders.AppFilterIconPackInstaller$buildIconPack$2.invokeSuspend(AppFilterIconPackInstaller.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
```

**Comment by Resaltare** [comment]
I have the same issue.
The icons that are not completely drawn change every time, haven't seen any pattern.

Stock S25 with latest updates (android 15)
Latest compiled version of the launcher from here
I have Tigad icon pack installed and allied if that matters.

![Image](https://github.com/user-attachments/assets/d5284452-782d-4575-856d-eca277afc931)
