### ISSUE TITLE
Crash during scrolling

### ISSUE THREAD

**Issue by GamePlayer-8** [MM2-0/Kvaesitso#933]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

Crashed when scrolling and randomly pressing 2 fullscreen apps as once.

## Strack trace

```
java.lang.IllegalArgumentException: Error: Uninitialized LayoutCoordinates. Please make sure when using the SharedTransitionScope composable function, the modifier passed to the child content is being used, or use SharedTransitionLayout instead.
	at androidx.compose.animation.SharedBoundsNode$measure$1.invoke(SharedContentNode.kt:73)
	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(LookaheadDelegate.kt:7)
	at androidx.compose.ui.node.LookaheadDelegate.placeChildren(LookaheadDelegate.kt:5)
	at androidx.compose.ui.node.LookaheadDelegate.placeAt-f8xVGno(LookaheadDelegate.kt:9)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:15)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate$placeSelf$2.invoke(LayoutNodeLayoutDelegate.kt:60)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:114)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.placeSelf-MLgxB_4$1(LayoutNodeLayoutDelegate.kt:104)
	at androidx.compose.ui.node.LayoutNode.lookaheadReplace$ui_release(LayoutNode.kt:35)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:41)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:44)
[18 lines truncated]
```

## Device info
APP.VERSION : 1.31.1<br>APP.VERSIONCODE : 2024070100<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Warsaw<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : A405FNXXU4CWC3<br>VERSION.SDK.NUMBER : 30<br>BOARD : exynos7904<br>BOOTLOADER : A405FNXXU4CWC3<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : RP1A.200720.012.A405FNXXU4CWC3<br>FINGERPRINT : samsung/a40eea/a40:11/RP1A.200720.012/A405FNXXU4CWC3:user/release-keys<br>HARDWARE : exynos7904<br>HOST : VPDJR104<br>ID : RP1A.200720.012<br>MANUFACTURER : samsung<br>MODEL : SM-A405FN<br>PRODUCT : a40eea<br>TAGS : release-keys<br>TIME : 1679623250000<br>TYPE : user

**Comment by MM2-0** [comment]
Outdated version
