### ISSUE TITLE
Layout Coordinates Crash

### ISSUE THREAD

**Issue by linuzzx** [MM2-0/Kvaesitso#936]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

Sometimes when I navigate my launcher and phone, Kvaisitso crashes and freezes until I relog into my phone

[kvaesitso-log-2024-07-10-062345.txt](https://github.com/user-attachments/files/16155299/kvaesitso-log-2024-07-10-062345.txt)

## Strack trace

```
java.lang.IllegalArgumentException: Error: Uninitialized LayoutCoordinates. Please make sure when using the SharedTransitionScope composable function, the modifier passed to the child content is being used, or use SharedTransitionLayout instead.
	at androidx.compose.animation.SharedBoundsNode$measure$1.invoke(SharedContentNode.kt:73)
	at androidx.compose.ui.node.LookaheadCapablePlaceable$layout$1.placeChildren(LookaheadDelegate.kt:7)
	at androidx.compose.ui.node.LookaheadDelegate.placeChildren(LookaheadDelegate.kt:5)
	at androidx.compose.ui.node.LookaheadDelegate.placeAt-f8xVGno(LookaheadDelegate.kt:9)
	at androidx.compose.ui.layout.Placeable$PlacementScope.place-70tqf50$default(Placeable.kt:15)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate$placeSelf$2.invoke(LayoutNodeLayoutDelegate.kt:60)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:114)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$LookaheadPassDelegate.placeSelf-MLgxB_4$1(LayoutNodeLayoutDelegate.kt:104)
	at androidx.compose.ui.node.LayoutNode.lookaheadReplace$ui_release(LayoutNode.kt:35)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:41)
	at androidx.compose.ui.node.MeasureAndLayoutDelegate.ensureSubtreeLookaheadReplaced(MeasureAndLayoutDelegate.kt:44)
[19 lines truncated]
```

## Device info
APP.VERSION : 1.31.2<br>APP.VERSIONCODE : 2024070300<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 76<br>VERSION.SDK.NUMBER : 34<br>BOARD : venus<br>BOOTLOADER : unknown<br>BRAND : Xiaomi<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : AP1A.240505.005<br>FINGERPRINT : Xiaomi/venus_global/venus:13/RKQ1.211001.001/V816.0.2.0.UKBMIXM:user/release-keys<br>HARDWARE : qcom<br>HOST : android-build<br>ID : AP1A.240505.005<br>MANUFACTURER : Xiaomi<br>MODEL : M2011K2G<br>PRODUCT : venus_global<br>TAGS : release-keys<br>TIME : 1718024277000<br>TYPE : user

**Comment by 8227846265** [comment]
I have the same issue. Had to temporarily switch to another launcher since the frequency of this issue is too high on my devices.
