### ISSUE TITLE
Crash on editing favourites 

### ISSUE THREAD

**Issue by Jabster28** [MM2-0/Kvaesitso#954]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

I had an app shortcut in my favourites menu that was removed when i freezed the app with [Hail](https://github.com/aistra0528/Hail). I tried to add the shortcut back after unfreezing the app, which worked, but now the launcher crashes whenever I press the editor button in the favourites list in the app drawer.

## Strack trace

```
org.json.JSONException: No value for image
	at org.json.JSONObject.get(JSONObject.java:398)
	at org.json.JSONObject.getString(JSONObject.java:559)
	at de.mm20.launcher2.websites.WebsiteDeserializer.deserialize(WebsiteSerialization.kt:40)
	at de.mm20.launcher2.searchable.SavableSearchableRepositoryImpl.access$fromDatabaseEntity(SavableSearchableRepository.kt:151)
	at de.mm20.launcher2.searchable.SavableSearchableRepositoryImpl$get$$inlined$map$1$2.emit(Emitters.kt:111)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:17)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:129)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:24)
	at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:3)
[10 lines truncated]
```

## Device info
APP.VERSION : 1.31.1<br>APP.VERSIONCODE : 2024070100<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/London<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 11860263<br>VERSION.SDK.NUMBER : 34<br>BOARD : oriole<br>BOOTLOADER : slider-14.5-11677881<br>BRAND : google<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : AP2A.240605.024<br>FINGERPRINT : google/oriole/oriole:14/AP2A.240605.024/11860263:user/release-keys<br>HARDWARE : oriole<br>HOST : r-82b05a39f2cf359a-4258<br>ID : AP2A.240605.024<br>MANUFACTURER : Google<br>MODEL : Pixel 6<br>PRODUCT : oriole<br>TAGS : release-keys<br>TIME : 1716016311000<br>TYPE : user

**Comment by MM2-0** [comment]
Outdated version, fixed in 1.31.2
