### ISSUE TITLE
Crash when typing to start an app

### ISSUE THREAD

**Issue by huettenwirt** [MM2-0/Kvaesitso#962]
## Description

*Please provide as many information about the crash

After typing the second character of a search, Kvaesitso crashes.

## Strack trace

```
java.lang.IllegalArgumentException: Key "calendar-calendar://27938" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:146)
	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(LazyLayoutMeasureScope.kt:34)
	at androidx.compose.foundation.lazy.LazyListMeasuredItemProvider.getAndMeasure-0kLqBqw$default(LazyListMeasuredItemProvider.kt:15)
	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:819)
	at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$3$2$1.invoke(LazyLayout.kt:21)
	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:74)
	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:50)
	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:1)
	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:189)
	at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasureBlock$1.invoke(LayoutNodeLayoutDelegate.kt:9)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:56)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:48)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:141)
	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:3)
[80 lines truncated]
```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : S906BXXSAEXEC<br>VERSION.SDK.NUMBER : 34<br>BOARD : s5e9925<br>BOOTLOADER : S906BXXSAEXEC<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.S906BXXSAEXEC<br>FINGERPRINT : samsung/g0sxeea/g0s:14/UP1A.231005.007/S906BXXSAEXEC:user/release-keys<br>HARDWARE : s5e9925<br>HOST : 21DK7923<br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-S906B<br>PRODUCT : g0sxeea<br>TAGS : release-keys<br>TIME : 1717045477000<br>TYPE : user

**Comment by matthewdavis** [comment]
I have this issue. I was able to work around it by disabling calendar from the search options.

Options -> Search -> uncheck calendar

After that I could search for apps

**Comment by huettenwirt** [comment]
Thanks for pointing this out. I was deleting the calendar widget, but didn't think of the calendar search. I'm sure this will be fixed, soon since there are multiple issues around this topic now...
