### ISSUE TITLE
instant crash after updating to 1.32.0 (F-Droid)

### ISSUE THREAD

**Issue by quantenzitrone** [MM2-0/Kvaesitso#990]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*

Nothing specific, I just used my phone after automatic background updates.

## Strack trace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object kotlinx.coroutines.sync.MutexImpl.lock(java.lang.Object, kotlin.coroutines.Continuation)' on a null object reference
	at de.mm20.launcher2.profiles.ProfileManager.access$refreshProfiles(ProfileManager.kt:69)
	at de.mm20.launcher2.profiles.ProfileManager$2.invokeSuspend(ProfileManager.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@871dd66, Dispatchers.Default]

```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : dRIzg4UiJzwGibzTylZTobfZl/E=<br>LAUNCHER.APP : com.saggitt.omega<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 8.1.0<br>VERSION.INCREMENTAL : 1682057242<br>VERSION.SDK.NUMBER : 27<br>BOARD : unknown<br>BOOTLOADER : unknown<br>BRAND : SHIFT<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : SHIFT6M.SOS.2.0.L.20230421<br>FINGERPRINT : SHIFT/SHIFT6m_EEA/SHIFT6m:8.1.0/OC/1682057242:user/release-keys<br>HARDWARE : mt6797<br>HOST : shiftphones.com<br>ID : OC<br>MANUFACTURER : SHIFT<br>MODEL : SHIFT6m<br>PRODUCT : SHIFT6m_EEA<br>TAGS : release-keys<br>TIME : 1682057238000<br>TYPE : user

**Comment by MM2-0** [comment]
Duplicate of #967
